// ale_kotlin_coroutines_module.kt — Niblit ALE Kotlin module
//
// Auto-generated by Niblit ALE.
// Demonstrates idiomatic Kotlin patterns: data classes, sealed classes,
// extension functions, coroutines (kotlinx.coroutines), and generics —
// compatible with Kotlin 1.9+ / JVM 11+ / Android.

package niblitale

import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking

// ── Data / sealed types ───────────────────────────────────────────────────

sealed class AleResult<out T> {
    data class Success<T>(val value: T) : AleResult<T>()
    data class Failure(val reason: String) : AleResult<Nothing>()
}

data class AleModuleSnapshot(
    val name: String,
    val entryCount: Int,
    val createdAtMs: Long = System.currentTimeMillis()
)

// ── Generic key-value store ───────────────────────────────────────────────

/**
 * Generic key-value store — canonical ALE Kotlin module.
 */
class AleKotlinModule<V>(val name: String = "ale_kotlin_module") {

    private val data: MutableMap<String, V> = mutableMapOf()
    private val createdAt: Long = System.currentTimeMillis()

    val entryCount: Int get() = data.size

    val ageSeconds: Double get() = (System.currentTimeMillis() - createdAt) / 1_000.0

    /** Store a value under [key]. */
    fun set(key: String, value: V): AleKotlinModule<V> {
        require(key.isNotEmpty()) { "key must not be empty" }
        data[key] = value
        return this
    }

    /** Retrieve a value; returns null when not found. */
    fun get(key: String): V? = data[key]

    /** Return all keys with an optional [prefix] filter. */
    fun keys(prefix: String = ""): List<String> =
        if (prefix.isEmpty()) data.keys.toList()
        else data.keys.filter { it.startsWith(prefix) }

    fun stats(): String = "%-24s: %d entries, age=%.1fs".format(name, entryCount, ageSeconds)

    fun snapshot(): AleModuleSnapshot =
        AleModuleSnapshot(name = name, entryCount = entryCount)

    /** Coroutine-based async runner. */
    suspend fun runAsync(delayMs: Long = 10L): AleResult<String> {
        delay(delayMs)
        return AleResult.Success(stats())
    }
}

// ── Extension functions ───────────────────────────────────────────────────

/** Pretty-print an [AleResult]. */
fun <T> AleResult<T>.display(): String = when (this) {
    is AleResult.Success -> "OK: $value"
    is AleResult.Failure -> "ERR: $reason"
}

// ── Entry point ───────────────────────────────────────────────────────────

fun main() = runBlocking {
    val m = AleKotlinModule<String>(name = "ale_kotlin_module")
    m.set("topic", "Kotlin coroutines and JVM patterns")
     .set("language", "kotlin")
     .set("runtime", "Kotlin 1.9+")

    println(m.stats())
    println("keys: ${m.keys().joinToString()}")

    val result = m.runAsync()
    println("async: ${result.display()}")

    val snap = m.snapshot()
    println("snapshot: $snap")
}
