//! ale_rust_async_programming_and_tokio — async programming and tokio
//!
//! Auto-generated by Niblit ALE.
//! Research: ✅ Researched rust async programming and tokio: 2 result(s) fetched. First result: No data found for 'rust async...

use std::collections::HashMap;
use std::error::Error;
use std::time::{SystemTime, UNIX_EPOCH};

/// AleRustAsyncProgrammingAndTokio implements: async programming and tokio
pub struct AleRustAsyncProgrammingAndTokio {
    name: String,
    data: HashMap<String, String>,
    created_at: u64,
}

impl AleRustAsyncProgrammingAndTokio {
    /// Create a new instance.
    pub fn new(name: impl Into<String>) -> Self {
        let ts = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0);
        Self {
            name: name.into(),
            data: HashMap::new(),
            created_at: ts,
        }
    }

    /// Store a key-value pair.
    pub fn set(&mut self, key: impl Into<String>, value: impl Into<String>) {
        self.data.insert(key.into(), value.into());
    }

    /// Retrieve a value by key.
    pub fn get(&self, key: &str) -> Option<&str> {
        self.data.get(key).map(String::as_str)
    }

    /// Return basic statistics as a formatted string.
    pub fn stats(&self) -> String {
        format!("{}: {} entries, created={}",
                self.name, self.data.len(), self.created_at)
    }
}

fn main() -> Result<(), Box<dyn Error>> {
    let mut m = AleRustAsyncProgrammingAndTokio::new("ale_rust_async_programming_and_tokio");
    m.set("topic", "async programming and tokio");
    println!("{}", m.stats());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_set_get() {
        let mut m = AleRustAsyncProgrammingAndTokio::new("test");
        m.set("key", "value");
        assert_eq!(m.get("key"), Some("value"));
    }
}