#!/usr/bin/env python3
"""
modules/goal_engine.py — Goal-Driven Cognition Engine for Niblit
================================================================
Transforms Niblit from a purely reactive learner ("process what comes in")
into a goal-driven agent ("decide what to learn next and why").

The GoalEngine analyses the current knowledge state and generates a
prioritised list of learning *objectives* — each describing:

  * **what** to learn (a topic or capability gap)
  * **why** it matters (rationale derived from the KB state)
  * **how urgent** it is (priority score 0–1)
  * **what type** of goal it is (``gap``, ``reinforce``, ``explore``,
    ``capability``)

Objective sources (in priority order)
--------------------------------------
1. **Metacognition gaps** — topics flagged as ``poorly_understood`` by the
   ``Metacognition`` module (ALE Step 17).
2. **Reasoning contradictions** — subjects where the ReasoningEngine found
   conflicting facts; resolution is a high-priority goal.
3. **Low-confidence KB facts** — facts whose reward-model score is below the
   threshold; these need to be reinforced or corrected.
4. **Underexplored domains** — KB prefix counts reveal which topic areas are
   thin; the engine generates "explore" goals for sparse domains.
5. **Capability gaps** — hard-coded gap analysis against the current pipeline
   stages (see ``_CAPABILITY_GAPS``).

Integration
-----------
``GoalEngine.generate_goals()`` is called by :class:`CognitionCore` once per
cognitive cycle.  The returned ``Goal`` objects are stored in
``ALE._cross_cycle_context["goal_objectives"]`` so that Phase A of the next
ALE cycle can seed its research queue with the highest-priority goals.

Usage::

    from modules.goal_engine import GoalEngine

    engine = GoalEngine()
    goals = engine.generate_goals(knowledge_db=kb, ale_context=ctx)
    for g in goals[:3]:
        print(g.priority, g.topic, g.rationale)

Singleton via ``get_goal_engine()``.

Configuration (environment variables)::

    NIBLIT_GOAL_MAX_GOALS           — Max goals returned per cycle (default 10)
    NIBLIT_GOAL_LOW_SCORE_THRESHOLD — KB score threshold for reinforce goals
                                      (default 0.35)
    NIBLIT_GOAL_EXPLORE_MIN_FACTS   — Domain facts below this triggers explore
                                      goal (default 3)
"""

from __future__ import annotations

import logging
import threading
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

log = logging.getLogger(__name__)

import os

_MAX_GOALS = int(os.environ.get("NIBLIT_GOAL_MAX_GOALS", "10"))
_LOW_SCORE_THRESHOLD = float(os.environ.get("NIBLIT_GOAL_LOW_SCORE_THRESHOLD", "0.35"))
_EXPLORE_MIN_FACTS = int(os.environ.get("NIBLIT_GOAL_EXPLORE_MIN_FACTS", "3"))

# ── Capability gaps: hard-coded known pipeline stages ─────────────────────────
# Each entry is (capability_key, description, suggested_topic)
_CAPABILITY_GAPS = [
    ("pre-training", "Domain tokenizer not trained", "sentencepiece tokenizer training"),
    ("training-infra", "LoRA/QLoRA not active (LOCAL_MODEL_PATH unset)", "LoRA fine-tuning peft trl"),
    ("transformer-market-model", "No TFT market forecast wired into TradingBrain", "temporal fusion transformer forecasting"),
    ("risk-management", "Kelly position sizing newly added, needs calibration", "Kelly criterion win rate estimation"),
    ("lm-eval", "lm-eval-harness evaluation not yet run", "lm eval harness mmlu hellaswag benchmark"),
]

# ── KB prefixes used for domain coverage analysis ─────────────────────────────
_DOMAIN_PREFIXES = {
    "research":    "ale_research:",
    "reflection":  "ale_reflection:",
    "knowledge":   "topic_knowledge:",
    "llm_train":   "ale_llm_train:",
    "metacog":     "ale_metacognition:",
    "trading":     "trading_state:",
    "code":        "ale_code:",
    "eval":        "ale_llm_eval:",
}


@dataclass
class Goal:
    """A single learning objective generated by the GoalEngine.

    Attributes
    ----------
    topic:       Short topic or concept phrase (used as ALE research topic).
    rationale:   Human-readable explanation of why this goal was generated.
    priority:    Urgency score in [0, 1].  Higher = more important.
    goal_type:   One of ``"gap"``, ``"reinforce"``, ``"explore"``,
                 ``"capability"``, ``"contradiction"``.
    source:      Which analysis source produced this goal.
    generated_at: UNIX timestamp of goal generation.
    """
    topic: str
    rationale: str
    priority: float
    goal_type: str = "gap"
    source: str = "goal_engine"
    generated_at: int = field(default_factory=lambda: int(time.time()))

    def to_dict(self) -> Dict[str, Any]:
        return {
            "topic": self.topic,
            "rationale": self.rationale,
            "priority": round(self.priority, 3),
            "goal_type": self.goal_type,
            "source": self.source,
            "generated_at": self.generated_at,
        }


class GoalEngine:
    """Dynamically generate and prioritise learning objectives for Niblit.

    Args:
        max_goals:            Maximum number of goals returned per cycle.
        low_score_threshold:  KB confidence score below which a fact becomes a
                              ``reinforce`` goal candidate.
        explore_min_facts:    Domain fact count below this number triggers an
                              ``explore`` goal for that domain.
    """

    def __init__(
        self,
        max_goals: int = _MAX_GOALS,
        low_score_threshold: float = _LOW_SCORE_THRESHOLD,
        explore_min_facts: int = _EXPLORE_MIN_FACTS,
    ) -> None:
        self.max_goals = max_goals
        self.low_score_threshold = low_score_threshold
        self.explore_min_facts = explore_min_facts

        self._lock = threading.Lock()
        self._last_goals: List[Goal] = []
        self._last_run_ts: Optional[int] = None
        self._total_goals_generated: int = 0

        log.info(
            "[GoalEngine] Initialised — max_goals=%d low_score=%.2f explore_min=%d",
            self.max_goals, self.low_score_threshold, self.explore_min_facts,
        )

    # ─────────────────────────────────────────────────────────────────────────
    # Primary API
    # ─────────────────────────────────────────────────────────────────────────

    def generate_goals(
        self,
        knowledge_db: Any = None,
        ale_context: Optional[Dict[str, Any]] = None,
        reasoning_engine: Any = None,
    ) -> List[Goal]:
        """Analyse the current knowledge state and return prioritised goals.

        Args:
            knowledge_db:     KnowledgeDB instance (or None).
            ale_context:      ALE ``_cross_cycle_context`` dict (or None).
                              Read for ``metacognition_gaps``,
                              ``reasoning_inferences``, and ``cognitive_domains``.
            reasoning_engine: Optional ReasoningEngine used to check for
                              contradictions among recent facts.

        Returns:
            Sorted list of :class:`Goal` objects (highest priority first),
            capped at :attr:`max_goals`.
        """
        with self._lock:
            goals: List[Goal] = []

            # 1. Metacognition gap goals (highest priority)
            goals.extend(self._goals_from_metacognition(ale_context or {}))

            # 2. Contradiction resolution goals
            goals.extend(self._goals_from_contradictions(reasoning_engine))

            # 3. Low-confidence KB fact reinforcement goals
            goals.extend(self._goals_from_low_confidence_facts(knowledge_db))

            # 4. Domain exploration goals (sparse KB areas)
            goals.extend(self._goals_from_domain_coverage(knowledge_db))

            # 5. Capability gap goals (hard-coded pipeline stages)
            goals.extend(self._goals_from_capability_gaps())

            # De-duplicate by topic (keep highest priority per topic)
            seen: Dict[str, Goal] = {}
            for g in goals:
                key = g.topic.lower().strip()
                if key not in seen or g.priority > seen[key].priority:
                    seen[key] = g
            unique_goals = sorted(seen.values(), key=lambda g: g.priority, reverse=True)

            result = unique_goals[:self.max_goals]
            self._last_goals = result
            self._last_run_ts = int(time.time())
            self._total_goals_generated += len(result)

            log.info(
                "[GoalEngine] Generated %d goals (%d unique topics from %d candidates)",
                len(result), len(seen), len(goals),
            )
            # Emit goals to SyncEngine so all devices share the same goal state
            try:
                from modules.sync_engine import get_sync_engine, SyncArtifact
                se = get_sync_engine()
                se.queue_artifact(SyncArtifact(
                    type="goal_engine_cycle",
                    content={
                        "goals_count": len(result),
                        "top_topics": [g.topic for g in result[:5]],
                    },
                    priority=0.45,
                    source="local",
                ))
            except Exception:
                pass
            return result

    # ─────────────────────────────────────────────────────────────────────────
    # Goal source: metacognition gaps
    # ─────────────────────────────────────────────────────────────────────────

    def _goals_from_metacognition(self, ale_context: Dict[str, Any]) -> List[Goal]:
        """Convert metacognition gap topics from ALE context into goals."""
        gaps = ale_context.get("metacognition_gaps", [])
        goals = []
        for i, topic in enumerate(gaps[:5]):
            if not topic:
                continue
            # First gap is most urgent; priority decreases linearly
            priority = 0.90 - i * 0.05
            goals.append(Goal(
                topic=str(topic),
                rationale=f"Metacognition identified '{topic}' as poorly understood",
                priority=priority,
                goal_type="gap",
                source="metacognition",
            ))
        return goals

    # ─────────────────────────────────────────────────────────────────────────
    # Goal source: reasoning contradictions
    # ─────────────────────────────────────────────────────────────────────────

    def _goals_from_contradictions(self, reasoning_engine: Any) -> List[Goal]:
        """Ask ReasoningEngine for contradictions and convert them into goals."""
        if reasoning_engine is None:
            return []
        goals = []
        try:
            contradictions = reasoning_engine.detect_contradictions()
            for c in contradictions[:3]:
                topic_a = getattr(c, "concept_a", None) or str(c)
                topic_b = getattr(c, "concept_b", None) or ""
                topic = f"{topic_a} vs {topic_b}".strip(" vs")
                rationale = (
                    getattr(c, "explanation", None)
                    or f"Contradiction detected between '{topic_a}' and '{topic_b}'"
                )
                goals.append(Goal(
                    topic=topic,
                    rationale=rationale,
                    priority=0.85,
                    goal_type="contradiction",
                    source="reasoning_contradictions",
                ))
        except Exception as exc:
            log.debug("[GoalEngine] contradiction check failed: %s", exc)
        return goals

    # ─────────────────────────────────────────────────────────────────────────
    # Goal source: low-confidence KB facts
    # ─────────────────────────────────────────────────────────────────────────

    def _goals_from_low_confidence_facts(self, knowledge_db: Any) -> List[Goal]:
        """Scan KB for facts with low confidence scores → reinforce goals."""
        if knowledge_db is None:
            return []
        goals = []
        try:
            # Try to get facts with a score/confidence field
            raw = []
            if hasattr(knowledge_db, "list_facts"):
                raw = knowledge_db.list_facts(200) or []
            elif hasattr(knowledge_db, "search"):
                for prefix in ("topic_knowledge:", "ale_research:"):
                    raw.extend(knowledge_db.search(prefix) or [])

            low_confidence_topics: List[str] = []
            for f in raw:
                if isinstance(f, dict):
                    score = f.get("score", f.get("confidence", f.get("quality", 1.0)))
                    key = f.get("key", f.get("id", ""))
                    if isinstance(score, (int, float)) and float(score) < self.low_score_threshold:
                        topic = str(key).split(":")[-1] if ":" in str(key) else str(key)
                        if topic and len(topic) > 3:
                            low_confidence_topics.append(topic)

            for topic in low_confidence_topics[:3]:
                goals.append(Goal(
                    topic=topic,
                    rationale=f"Low confidence score in KB for '{topic}' — needs reinforcement",
                    priority=0.70,
                    goal_type="reinforce",
                    source="low_confidence_kb",
                ))
        except Exception as exc:
            log.debug("[GoalEngine] low-confidence scan failed: %s", exc)
        return goals

    # ─────────────────────────────────────────────────────────────────────────
    # Goal source: domain coverage analysis
    # ─────────────────────────────────────────────────────────────────────────

    def _goals_from_domain_coverage(self, knowledge_db: Any) -> List[Goal]:
        """Identify sparse KB domains → exploration goals."""
        if knowledge_db is None:
            return []
        goals = []
        try:
            domain_counts: Dict[str, int] = {}
            for domain, prefix in _DOMAIN_PREFIXES.items():
                count = 0
                if hasattr(knowledge_db, "search"):
                    results = knowledge_db.search(prefix) or []
                    count = len(results) if isinstance(results, list) else 0
                elif hasattr(knowledge_db, "list_keys"):
                    keys = knowledge_db.list_keys() or []
                    count = sum(1 for k in keys if str(k).startswith(prefix))
                domain_counts[domain] = count

            # Domains with fewer than explore_min_facts entries
            sparse = [
                (domain, cnt)
                for domain, cnt in domain_counts.items()
                if cnt < self.explore_min_facts
            ]
            for domain, cnt in sorted(sparse, key=lambda x: x[1]):
                suggested_topic = domain.replace("_", " ")
                goals.append(Goal(
                    topic=suggested_topic,
                    rationale=(
                        f"Domain '{domain}' has only {cnt} KB entries "
                        f"(below explore threshold of {self.explore_min_facts})"
                    ),
                    priority=0.40 + (self.explore_min_facts - cnt) * 0.05,
                    goal_type="explore",
                    source="domain_coverage",
                ))
        except Exception as exc:
            log.debug("[GoalEngine] domain coverage failed: %s", exc)
        return goals

    # ─────────────────────────────────────────────────────────────────────────
    # Goal source: capability gaps
    # ─────────────────────────────────────────────────────────────────────────

    def _goals_from_capability_gaps(self) -> List[Goal]:
        """Emit goals for known pipeline capability gaps."""
        goals = []
        for capability, description, topic in _CAPABILITY_GAPS:
            # Only surface the gap if the env variable controlling that
            # capability is not set (keeps noise low when already active)
            skip = False
            if capability == "training-infra" and os.environ.get("LOCAL_MODEL_PATH"):
                skip = True
            if not skip:
                goals.append(Goal(
                    topic=topic,
                    rationale=description,
                    priority=0.50,
                    goal_type="capability",
                    source="capability_gap_analysis",
                ))
        return goals

    # ─────────────────────────────────────────────────────────────────────────
    # Status and persistence
    # ─────────────────────────────────────────────────────────────────────────

    def status(self) -> Dict[str, Any]:
        """Return a status dict for this engine."""
        with self._lock:
            return {
                "max_goals": self.max_goals,
                "low_score_threshold": self.low_score_threshold,
                "explore_min_facts": self.explore_min_facts,
                "last_run_ts": self._last_run_ts,
                "total_goals_generated": self._total_goals_generated,
                "last_goals": [g.to_dict() for g in self._last_goals[:5]],
            }

    def top_topics(self, n: int = 5) -> List[str]:
        """Return the topic strings for the top *n* most recent goals."""
        with self._lock:
            return [g.topic for g in self._last_goals[:n]]


# ── Singleton ─────────────────────────────────────────────────────────────────
_engine: Optional[GoalEngine] = None
_engine_lock = threading.Lock()


def get_goal_engine(**kwargs) -> GoalEngine:
    """Return the process-level :class:`GoalEngine` singleton."""
    global _engine  # pylint: disable=global-statement
    with _engine_lock:
        if _engine is None:
            _engine = GoalEngine(**kwargs)
        return _engine


if __name__ == "__main__":
    print('Running goal_engine.py')
