#!/usr/bin/env python3
"""
modules/lean_deploy_engine.py — QuantConnect Cloud Live-Trade Deployment Engine.

Provides :class:`LeanDeployEngine`, a complete integration layer between
Niblit's trading brain and the QuantConnect REST API v2 (https://quantconnect.com/api/v2/).

This module complements the existing :class:`~modules.lean_engine.LeanEngine`
(CLI wrapper) by talking directly to the QuantConnect REST API so Niblit can:

* **Compile** algorithm source code on the QC cloud.
* **Create / list / read / stop** live trading deployments.
* **Liquidate** a live algorithm's positions.
* **Download backtest results** via REST for analysis.
* **Push algorithm updates** to existing cloud projects.
* **Self-monitor** running live algorithms and feed results back to
  Niblit's knowledge base and reflection engine.

Authentication
--------------
QuantConnect REST API v2 uses HTTP Basic Auth with HMAC-SHA256 time-stamped
token:

    Authorization: Basic base64(userId + ":" + sha256(timestamp + ":" + apiToken))

Set the following env vars (or niblit_params.json keys):

    QC_USER_ID   — QuantConnect user ID (integer string).
    QC_API_TOKEN — QuantConnect API token (generated in the dashboard).

Both are required for any cloud operation.  Without them, all methods return
descriptive error strings.

Project / Algorithm structure (QuantConnect / LEAN Python)
----------------------------------------------------------
A LEAN Python algorithm must:

1.  **Import AlgorithmImports**:
    ``from AlgorithmImports import *``

2.  **Extend QCAlgorithm** with a named class, e.g.:
    ``class MyStrategy(QCAlgorithm):``

3.  **Implement ``initialize``** — sets date range, cash, subscriptions,
    and indicators.

4.  **Implement ``on_data(data)``** — called on every new bar/tick.

5.  **Optionally** implement ``on_order_event``, ``on_end_of_algorithm``.

All algorithms generated by this module follow this exact structure and are
compatible with local ``lean backtest`` as well as cloud deployment.
"""

from __future__ import annotations

import base64
import hashlib
import json
import logging
import os
import threading
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

import requests

log = logging.getLogger("LeanDeployEngine")

# ── optional parameter manager ────────────────────────────────────────────────
try:
    from modules.parameter_manager import parameter_manager as _pm
except ImportError:
    _pm = None  # type: ignore[assignment]

# ── notification queue ────────────────────────────────────────────────────────
try:
    from core.notification_queue import notif_queue as _notif_queue
except ImportError:
    class _NopQueue:
        def push(self, msg: str) -> None:
            pass
    _notif_queue = _NopQueue()  # type: ignore[assignment]

# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────

_QC_API_BASE = "https://www.quantconnect.com/api/v2"
_DEFAULT_MONITOR_INTERVAL_SECS = 60   # how often to poll live algorithm status

# ─────────────────────────────────────────────────────────────────────────────
# LEAN Algorithm templates (QCAlgorithm subclasses)
# ─────────────────────────────────────────────────────────────────────────────

# Basic equity EMA crossover (live/backtest compatible)
_TEMPLATE_EMA_CROSSOVER = '''\
from AlgorithmImports import *


class {class_name}(QCAlgorithm):
    """Niblit EMA Crossover — {description}"""

    def initialize(self):
        self.set_start_date({start_year}, {start_month}, {start_day})
        self.set_end_date({end_year}, {end_month}, {end_day})
        self.set_cash({initial_cash})
        self.add_equity("{symbol}", Resolution.DAILY)
        self.fast_ema = self.ema("{symbol}", {fast_period}, Resolution.DAILY)
        self.slow_ema = self.ema("{symbol}", {slow_period}, Resolution.DAILY)

    def on_data(self, data):
        if not (self.fast_ema.is_ready and self.slow_ema.is_ready):
            return
        holdings = self.portfolio["{symbol}"].quantity
        if self.fast_ema.current.value > self.slow_ema.current.value and holdings <= 0:
            self.set_holdings("{symbol}", 1)
        elif self.fast_ema.current.value < self.slow_ema.current.value and holdings > 0:
            self.liquidate("{symbol}")

    def on_order_event(self, order_event):
        self.log(str(order_event))

    def on_end_of_algorithm(self):
        self.log(f"Final portfolio value: {{self.portfolio.total_portfolio_value}}")
'''

# Crypto EMA crossover (Binance / GDAX)
_TEMPLATE_CRYPTO_EMA = '''\
from AlgorithmImports import *


class {class_name}(QCAlgorithm):
    """Niblit Crypto EMA Crossover — {description}"""

    def initialize(self):
        self.set_start_date({start_year}, {start_month}, {start_day})
        self.set_end_date({end_year}, {end_month}, {end_day})
        self.set_cash({initial_cash})
        self.set_brokerage_model(BrokerageName.{brokerage}, AccountType.CASH)
        self.add_crypto("{symbol}", Resolution.MINUTE)
        self.fast_ema = self.ema("{symbol}", {fast_period}, Resolution.MINUTE)
        self.slow_ema = self.ema("{symbol}", {slow_period}, Resolution.MINUTE)

    def on_data(self, data):
        if not (self.fast_ema.is_ready and self.slow_ema.is_ready):
            return
        holdings = self.portfolio["{symbol}"].quantity
        if self.fast_ema > self.slow_ema and holdings <= 0:
            free_cash = self.portfolio.cash_book["USD"].amount * 0.95
            if free_cash > 0:
                price = self.securities["{symbol}"].price
                self.market_order("{symbol}", free_cash / price)
        elif self.fast_ema < self.slow_ema and holdings > 0:
            self.liquidate("{symbol}")

    def on_order_event(self, order_event):
        self.log(str(order_event))
'''

# Forex / CFD template (OANDA brokerage)
_TEMPLATE_FOREX = '''\
from AlgorithmImports import *


class {class_name}(QCAlgorithm):
    """Niblit Forex Strategy — {description}"""

    def initialize(self):
        self.set_start_date({start_year}, {start_month}, {start_day})
        self.set_end_date({end_year}, {end_month}, {end_day})
        self.set_cash({initial_cash})
        self.set_brokerage_model(BrokerageName.OANDA, AccountType.MARGIN)
        self.add_forex("{symbol}", Resolution.HOUR)
        self.fast_ema = self.ema("{symbol}", {fast_period}, Resolution.HOUR)
        self.slow_ema = self.ema("{symbol}", {slow_period}, Resolution.HOUR)
        self.rsi = self.rsi("{symbol}", 14, Resolution.HOUR)

    def on_data(self, data):
        if not (self.fast_ema.is_ready and self.slow_ema.is_ready and self.rsi.is_ready):
            return
        holdings = self.portfolio["{symbol}"].quantity
        cross_up = self.fast_ema.current.value > self.slow_ema.current.value
        cross_dn = self.fast_ema.current.value < self.slow_ema.current.value
        rsi_ok_buy = self.rsi.current.value < 70
        rsi_ok_sell = self.rsi.current.value > 30
        if cross_up and rsi_ok_buy and holdings <= 0:
            self.set_holdings("{symbol}", 1)
        elif cross_dn and rsi_ok_sell and holdings > 0:
            self.liquidate("{symbol}")

    def on_order_event(self, order_event):
        self.log(str(order_event))
'''

# Equity indices CFD template
_TEMPLATE_INDEX_CFD = '''\
from AlgorithmImports import *


class {class_name}(QCAlgorithm):
    """Niblit Index/CFD Momentum — {description}"""

    def initialize(self):
        self.set_start_date({start_year}, {start_month}, {start_day})
        self.set_end_date({end_year}, {end_month}, {end_day})
        self.set_cash({initial_cash})
        self.set_brokerage_model(BrokerageName.INTERACTIVE_BROKERS_BROKERAGE, AccountType.MARGIN)
        self.add_cfd("{symbol}", Resolution.HOUR)
        self.sma = self.sma("{symbol}", {slow_period}, Resolution.HOUR)
        self.macd = self.macd("{symbol}", {fast_period}, {slow_period}, 9, Resolution.HOUR)

    def on_data(self, data):
        if not (self.sma.is_ready and self.macd.is_ready):
            return
        holdings = self.portfolio["{symbol}"].quantity
        price = self.securities["{symbol}"].price
        macd_val = self.macd.current.value
        signal = self.macd.signal.current.value
        if price > self.sma.current.value and macd_val > signal and holdings <= 0:
            self.set_holdings("{symbol}", 1)
        elif (price < self.sma.current.value or macd_val < signal) and holdings > 0:
            self.liquidate("{symbol}")

    def on_order_event(self, order_event):
        self.log(str(order_event))
'''

# Multi-asset momentum template
_TEMPLATE_MULTI_ASSET = '''\
from AlgorithmImports import *


class {class_name}(QCAlgorithm):
    """Niblit Multi-Asset Momentum — {description}"""

    SYMBOLS = {symbols_repr}

    def initialize(self):
        self.set_start_date({start_year}, {start_month}, {start_day})
        self.set_end_date({end_year}, {end_month}, {end_day})
        self.set_cash({initial_cash})
        self.indicators = {{}}
        for sym in self.SYMBOLS:
            self.add_equity(sym, Resolution.DAILY)
            self.indicators[sym] = self.momp(sym, {momentum_period}, Resolution.DAILY)

    def on_data(self, data):
        scores = {{}}
        for sym, mom in self.indicators.items():
            if mom.is_ready:
                scores[sym] = mom.current.value
        if not scores:
            return
        ranked = sorted(scores, key=scores.get, reverse=True)
        top = ranked[:max(1, len(ranked) // 3)]
        target = 1.0 / max(len(top), 1)
        for sym in self.SYMBOLS:
            if sym in top:
                self.set_holdings(sym, target)
            else:
                self.liquidate(sym)
'''

_ALGO_TEMPLATES: Dict[str, str] = {
    "ema_crossover":  _TEMPLATE_EMA_CROSSOVER,
    "crypto_ema":     _TEMPLATE_CRYPTO_EMA,
    "forex_ema":      _TEMPLATE_FOREX,
    "index_cfd":      _TEMPLATE_INDEX_CFD,
    "multi_asset":    _TEMPLATE_MULTI_ASSET,
}


def _to_class_name(name: str) -> str:
    """Convert 'my-strategy' → 'MyStrategy'."""
    import re
    return "".join(w.capitalize() for w in re.split(r"[-_ ]+", name))


# ─────────────────────────────────────────────────────────────────────────────
# LeanDeployEngine
# ─────────────────────────────────────────────────────────────────────────────

class LeanDeployEngine:
    """QuantConnect REST API client and live-trade deployment manager.

    All network calls use HMAC-SHA256 authentication as required by the
    QuantConnect API v2.  Methods degrade gracefully when credentials are
    missing.

    Parameters
    ----------
    knowledge_db:   Optional KnowledgeDB for storing live-trade insights.
    reflect_module: Optional ReflectModule for post-trade reflection.
    """

    def __init__(
        self,
        knowledge_db: Optional[Any] = None,
        reflect_module: Optional[Any] = None,
    ) -> None:
        self._kb = knowledge_db
        self._reflect = reflect_module
        self._monitor_threads: Dict[str, threading.Thread] = {}
        self._lock = threading.Lock()
        log.info("[LeanDeploy] Initialized — QC_USER_ID=%s",
                 "set" if self._user_id() else "NOT SET")

    # ── credentials ──────────────────────────────────────────────────────────

    def _user_id(self) -> str:
        return (
            ((_pm.get("QC_USER_ID") if _pm else None) or "").strip()
            or os.environ.get("QC_USER_ID", "").strip()
        )

    def _api_token(self) -> str:
        return (
            ((_pm.get("QC_API_TOKEN") if _pm else None) or "").strip()
            or os.environ.get("QC_API_TOKEN", "").strip()
        )

    def _auth_header(self) -> Tuple[str, str]:
        """Return (Authorization header value, timestamp string)."""
        ts = str(int(time.time()))
        token = self._api_token()
        hash_bytes = hashlib.sha256(f"{ts}:{token}".encode()).hexdigest()
        raw = f"{self._user_id()}:{hash_bytes}"
        encoded = base64.b64encode(raw.encode()).decode()
        return f"Basic {encoded}", ts

    def _headers(self) -> Dict[str, str]:
        auth, ts = self._auth_header()
        return {
            "Authorization": auth,
            "Timestamp": ts,
            "Content-Type": "application/json",
        }

    def _has_credentials(self) -> bool:
        return bool(self._user_id() and self._api_token())

    def _creds_error(self) -> str:
        return (
            "[LeanDeploy] QC_USER_ID and QC_API_TOKEN must be set.\n"
            "Get them from: https://www.quantconnect.com/account\n"
            "Set via env vars or niblit_params.json."
        )

    # ── low-level API call ───────────────────────────────────────────────────

    def _api(
        self,
        method: str,
        endpoint: str,
        payload: Optional[Dict[str, Any]] = None,
        timeout: int = 30,
    ) -> Dict[str, Any]:
        """Execute a QC REST API call.

        Returns the parsed JSON response dict, or ``{"error": "…"}`` on
        failure.
        """
        if not self._has_credentials():
            return {"error": "credentials_missing"}
        url = f"{_QC_API_BASE}/{endpoint.lstrip('/')}"
        try:
            resp = requests.request(
                method.upper(),
                url,
                headers=self._headers(),
                json=payload,
                timeout=timeout,
            )
            try:
                data = resp.json()
            except Exception:
                data = {"raw": resp.text, "status_code": resp.status_code}
            if not resp.ok:
                log.warning("[LeanDeploy] API %s %s → %s %s",
                            method, endpoint, resp.status_code, data)
            return data
        except requests.exceptions.RequestException as exc:
            log.error("[LeanDeploy] Request error %s %s: %s", method, endpoint, exc)
            return {"error": str(exc)}

    # ── status ────────────────────────────────────────────────────────────────

    def status(self) -> str:
        creds = "✅ set" if self._has_credentials() else "⚠️  not set (QC_USER_ID + QC_API_TOKEN)"
        active_monitors = sum(1 for t in self._monitor_threads.values() if t.is_alive())
        templates = list(_ALGO_TEMPLATES.keys())
        lines = [
            "=== LeanDeployEngine (QuantConnect REST API) ===",
            f"  Credentials:      {creds}",
            f"  Active monitors:  {active_monitors}",
            f"  Algorithm templates: {templates}",
            "",
            "  Required env vars:",
            "    QC_USER_ID    — QuantConnect numeric user ID",
            "    QC_API_TOKEN  — QuantConnect API token",
            "",
            "  Commands:",
            "    lean deploy status",
            "    lean deploy projects",
            "    lean deploy create <name> [<template>]",
            "    lean deploy backtest <projectId>",
            "    lean deploy live <projectId> <brokerage>",
            "    lean deploy live-list",
            "    lean deploy live-read <deployId>",
            "    lean deploy live-stop <deployId>",
            "    lean deploy liquidate <deployId>",
            "    lean deploy templates",
            "    lean deploy generate <template> <name> [symbol=X] [...]",
        ]
        return "\n".join(lines)

    # ── project management ────────────────────────────────────────────────────

    def list_projects(self) -> Any:
        """List all cloud projects for the authenticated user."""
        if not self._has_credentials():
            return self._creds_error()
        data = self._api("GET", "projects/read")
        if "error" in data:
            return f"[LeanDeploy] {data['error']}"
        projects = data.get("projects", [])
        if not projects:
            return "No QC cloud projects found."
        lines = ["QC Cloud Projects:"]
        for p in projects:
            pid = p.get("projectId", "?")
            name = p.get("name", "?")
            lang = p.get("language", "?")
            modified = p.get("modified", "?")
            lines.append(f"  [{pid}] {name}  ({lang})  — modified: {modified}")
        return "\n".join(lines)

    def create_project(self, name: str, language: str = "Py") -> Any:
        """Create a new QC cloud project.

        Returns the new project ID or an error string.
        """
        if not self._has_credentials():
            return self._creds_error()
        data = self._api("POST", "projects/create",
                         {"name": name, "language": language})
        if "error" in data:
            return f"[LeanDeploy] Create project error: {data['error']}"
        project = data.get("projects", [{}])[0]
        pid = project.get("projectId", "?")
        msg = f"✅ Created QC project '{name}' (projectId={pid})"
        log.info("[LeanDeploy] %s", msg)
        _notif_queue.push(msg)
        self._store_in_kb(f"lean_deploy:project:{pid}", msg)
        return msg

    def delete_project(self, project_id: int) -> Any:
        """Delete a QC cloud project by ID."""
        if not self._has_credentials():
            return self._creds_error()
        data = self._api("POST", "projects/delete", {"projectId": project_id})
        if data.get("success"):
            return f"✅ Deleted project {project_id}"
        return f"[LeanDeploy] Delete error: {data}"

    def update_project_files(
        self,
        project_id: int,
        files: List[Dict[str, str]],
    ) -> Any:
        """Upload / overwrite source files in a cloud project.

        *files*: list of ``{"name": "main.py", "content": "…"}``.
        """
        if not self._has_credentials():
            return self._creds_error()
        results = []
        for f in files:
            r = self._api("POST", "files/create", {
                "projectId": project_id,
                "name": f["name"],
                "content": f["content"],
            })
            if not r.get("success"):
                # Try update instead of create
                r = self._api("POST", "files/update", {
                    "projectId": project_id,
                    "name": f["name"],
                    "content": f["content"],
                })
            results.append(f"{f['name']}: {'✅' if r.get('success') else '⚠️'}")
        return "Files updated: " + ", ".join(results)

    # ── compilation ───────────────────────────────────────────────────────────

    def compile_project(self, project_id: int) -> Any:
        """Compile a cloud project and return compilation results."""
        if not self._has_credentials():
            return self._creds_error()
        data = self._api("POST", "compile/create", {"projectId": project_id})
        compile_id = data.get("compileId")
        if not compile_id:
            return f"[LeanDeploy] Compile failed: {data}"
        msg = f"⏳ Compiling project {project_id} (compileId={compile_id})"
        _notif_queue.push(msg)
        # Poll for completion (max 60 seconds)
        for _ in range(30):
            time.sleep(2)
            status_data = self._api("GET", f"compile/read?projectId={project_id}&compileId={compile_id}")
            state = status_data.get("state", "")
            if state == "BuildSuccess":
                ok = f"✅ Compile success: project {project_id}"
                _notif_queue.push(ok)
                return ok
            if state in ("BuildError", "error"):
                err = status_data.get("logs", str(status_data))
                return f"[LeanDeploy] Compile error: {err[:500]}"
        return f"[LeanDeploy] Compile timed out (compileId={compile_id})"

    # ── backtesting ───────────────────────────────────────────────────────────

    def create_backtest(
        self,
        project_id: int,
        compile_id: Optional[str] = None,
        name: Optional[str] = None,
    ) -> Any:
        """Launch a cloud backtest for a compiled project.

        Returns the backtest ID or error string.
        """
        if not self._has_credentials():
            return self._creds_error()
        payload: Dict[str, Any] = {"projectId": project_id}
        if compile_id:
            payload["compileId"] = compile_id
        if name:
            payload["backtestName"] = name
        data = self._api("POST", "backtests/create", payload)
        bt_id = data.get("backtestId")
        if not bt_id:
            return f"[LeanDeploy] Backtest create error: {data}"
        msg = f"⏳ Backtest started: project {project_id} (backtestId={bt_id})"
        _notif_queue.push(msg)
        return msg

    def read_backtest(self, project_id: int, backtest_id: str) -> Any:
        """Read backtest results."""
        if not self._has_credentials():
            return self._creds_error()
        data = self._api("GET", f"backtests/read?projectId={project_id}&backtestId={backtest_id}")
        if "error" in data:
            return f"[LeanDeploy] {data['error']}"
        # Extract key metrics
        bt = data.get("backtest", {})
        stats = bt.get("statistics", {})
        progress = bt.get("progress", 0)
        completed = bt.get("completed", False)
        lines = [
            f"Backtest {backtest_id}:",
            f"  Progress:     {progress*100:.1f}%",
            f"  Completed:    {completed}",
        ]
        for k, v in list(stats.items())[:10]:
            lines.append(f"  {k}: {v}")
        result = "\n".join(lines)
        if completed:
            self._store_in_kb(
                f"lean_deploy:backtest:{backtest_id}",
                f"QC backtest {backtest_id} (project {project_id}): " +
                ", ".join(f"{k}={v}" for k, v in list(stats.items())[:5]),
                tags=["lean", "backtest", "quantconnect"],
            )
        return result

    def list_backtests(self, project_id: int) -> Any:
        """List all backtests for a project."""
        if not self._has_credentials():
            return self._creds_error()
        data = self._api("GET", f"backtests/list?projectId={project_id}")
        backtests = data.get("backtests", [])
        if not backtests:
            return f"No backtests found for project {project_id}"
        lines = [f"Backtests for project {project_id}:"]
        for bt in backtests:
            bid = bt.get("backtestId", "?")
            name = bt.get("name", "?")
            created = bt.get("created", "?")
            completed = bt.get("completed", False)
            sharpe = bt.get("statistics", {}).get("Sharpe Ratio", "?")
            lines.append(f"  {bid} — {name}  (completed={completed}, sharpe={sharpe}, {created})")
        return "\n".join(lines)

    # ── live trading ──────────────────────────────────────────────────────────

    def create_live_algorithm(
        self,
        project_id: int,
        compile_id: str,
        brokerage: str = "PaperBrokerage",
        brokerage_settings: Optional[Dict[str, Any]] = None,
        base_live_algorithm_settings: Optional[Dict[str, Any]] = None,
        version_id: str = "-1",
    ) -> Any:
        """Deploy a compiled algorithm to live trading on QuantConnect cloud.

        Parameters
        ----------
        project_id:   Cloud project ID.
        compile_id:   Compile ID (from compile_project()).
        brokerage:    Brokerage name (e.g. ``PaperBrokerage``, ``Binance``,
                      ``OandaBrokerage``, ``InteractiveBrokersBrokerage``).
        brokerage_settings:
                      Brokerage-specific settings dict (API keys, account IDs).
        version_id:   LEAN engine version (``-1`` = latest).

        Returns str with deployment ID or error.
        """
        if not self._has_credentials():
            return self._creds_error()
        payload: Dict[str, Any] = {
            "projectId": project_id,
            "compileId": compile_id,
            "serverType": "L-MICRO",
            "baseLiveAlgorithmSettings": base_live_algorithm_settings or {},
            "versionId": version_id,
            "brokerage": {
                "id": brokerage,
                **(brokerage_settings or {}),
            },
        }
        data = self._api("POST", "live/create", payload)
        deploy_id = data.get("deployId")
        if not deploy_id:
            return f"[LeanDeploy] Live create error: {data}"
        msg = (
            f"✅ Live algorithm deployed: project={project_id} "
            f"brokerage={brokerage} deployId={deploy_id}"
        )
        log.info("[LeanDeploy] %s", msg)
        _notif_queue.push(msg)
        self._store_in_kb(
            f"lean_deploy:live:{deploy_id}",
            msg,
            tags=["lean", "live", "quantconnect"],
        )
        return msg

    def list_live_algorithms(self) -> Any:
        """List all live algorithm deployments for the authenticated user."""
        if not self._has_credentials():
            return self._creds_error()
        data = self._api("GET", "live/list")
        algorithms = data.get("liveAlgorithms", [])
        if not algorithms:
            return "No live algorithms found."
        lines = ["Live Algorithms:"]
        for a in algorithms:
            did = a.get("deployId", "?")
            pid = a.get("projectId", "?")
            status = a.get("status", "?")
            launched = a.get("launched", "?")
            brokerage = a.get("brokerage", "?")
            lines.append(f"  {did} — project {pid}  status={status}  brokerage={brokerage}  launched={launched}")
        return "\n".join(lines)

    def read_live_algorithm(self, project_id: int, deploy_id: str) -> Any:
        """Read current state / statistics of a live algorithm."""
        if not self._has_credentials():
            return self._creds_error()
        data = self._api("GET", f"live/read?projectId={project_id}&deployId={deploy_id}")
        if "error" in data:
            return f"[LeanDeploy] {data['error']}"
        live = data.get("liveAlgorithm", data)
        status = live.get("status", "?")
        runtime_stats = live.get("runtimeStatistics", {})
        holdings = live.get("holdings", {})
        lines = [
            f"Live Algorithm {deploy_id}:",
            f"  Status:   {status}",
        ]
        for k, v in list(runtime_stats.items())[:8]:
            lines.append(f"  {k}: {v}")
        if holdings:
            lines.append("  Holdings:")
            for sym, h in list(holdings.items())[:5]:
                lines.append(f"    {sym}: qty={h.get('quantity','?')} price={h.get('averagePrice','?')}")
        result = "\n".join(lines)
        self._store_in_kb(
            f"lean_deploy:live_status:{deploy_id}:{int(time.time())}",
            f"Live algorithm {deploy_id} status={status} stats={list(runtime_stats.items())[:4]}",
            tags=["lean", "live", "quantconnect"],
        )
        return result

    def stop_live_algorithm(self, project_id: int) -> Any:
        """Stop a running live algorithm."""
        if not self._has_credentials():
            return self._creds_error()
        data = self._api("POST", "live/stop", {"projectId": project_id})
        if data.get("success"):
            msg = f"✅ Stopped live algorithm for project {project_id}"
            _notif_queue.push(msg)
            return msg
        return f"[LeanDeploy] Stop error: {data}"

    def liquidate_live_algorithm(self, project_id: int) -> Any:
        """Liquidate all open positions of a live algorithm."""
        if not self._has_credentials():
            return self._creds_error()
        data = self._api("POST", "live/liquidate", {"projectId": project_id})
        if data.get("success"):
            msg = f"✅ Liquidated all positions for project {project_id}"
            _notif_queue.push(msg)
            return msg
        return f"[LeanDeploy] Liquidate error: {data}"

    # ── live order management ─────────────────────────────────────────────────

    def read_live_orders(self, project_id: int, start: int = 0, end: int = 100) -> Any:
        """Read orders placed by a live algorithm."""
        if not self._has_credentials():
            return self._creds_error()
        data = self._api("GET",
                         f"live/orders/read?projectId={project_id}&start={start}&end={end}")
        orders = data.get("orders", [])
        if not orders:
            return f"No orders for project {project_id}"
        lines = [f"Orders (project {project_id}):"]
        for o in orders:
            lines.append(
                f"  {o.get('id','?')} {o.get('symbol','?')} "
                f"qty={o.get('quantity','?')} "
                f"type={o.get('type','?')} "
                f"status={o.get('status','?')}"
            )
        return "\n".join(lines)

    # ── algorithm generation ──────────────────────────────────────────────────

    def generate_algorithm(
        self,
        template: str = "ema_crossover",
        name: str = "NiblitStrategy",
        **params: Any,
    ) -> str:
        """Generate LEAN Python algorithm source code from a template.

        Parameters
        ----------
        template:   One of: ema_crossover, crypto_ema, forex_ema, index_cfd,
                    multi_asset.
        name:       Strategy name (used as class name and description).
        **params:   Template-specific params (symbol, fast_period, etc.).

        Returns the Python source code string.
        """
        tpl = _ALGO_TEMPLATES.get(template)
        if tpl is None:
            return (
                f"[LeanDeploy] Unknown template '{template}'. "
                f"Available: {list(_ALGO_TEMPLATES.keys())}"
            )
        now = datetime.now(tz=timezone.utc)
        defaults: Dict[str, Any] = {
            "class_name": _to_class_name(name),
            "description": name,
            "symbol": params.get("symbol", "SPY"),
            "initial_cash": params.get("initial_cash", 100_000),
            "start_year": params.get("start_year", now.year - 3),
            "start_month": params.get("start_month", 1),
            "start_day": params.get("start_day", 1),
            "end_year": params.get("end_year", now.year),
            "end_month": params.get("end_month", now.month),
            "end_day": params.get("end_day", now.day),
            "fast_period": params.get("fast_period", 10),
            "slow_period": params.get("slow_period", 30),
            "momentum_period": params.get("momentum_period", 20),
            "brokerage": params.get("brokerage", "COINBASE"),
            "symbols_repr": repr(params.get("symbols", ["SPY", "QQQ", "IWM", "GLD"])),
        }
        try:
            return tpl.format(**defaults)
        except KeyError as exc:
            return f"[LeanDeploy] Template format error: {exc}"

    def list_templates(self) -> str:
        """List available LEAN algorithm templates."""
        lines = ["Available LEAN Algorithm Templates:"]
        descriptions = {
            "ema_crossover": "Equity EMA crossover (Binance/IBKR)",
            "crypto_ema":    "Crypto EMA crossover (Binance/Coinbase)",
            "forex_ema":     "Forex EMA + RSI (OANDA)",
            "index_cfd":     "Index/CFD MACD momentum (IBKR)",
            "multi_asset":   "Multi-asset cross-sectional momentum",
        }
        for k, v in descriptions.items():
            lines.append(f"  {k:<20} — {v}")
        lines += [
            "",
            "Usage: lean deploy generate <template> <name> [symbol=X] [fast_period=N] [...]",
        ]
        return "\n".join(lines)

    # ── continuous monitoring ─────────────────────────────────────────────────

    def start_monitor(
        self,
        project_id: int,
        deploy_id: str,
        interval_secs: int = _DEFAULT_MONITOR_INTERVAL_SECS,
    ) -> str:
        """Start a background thread that polls a live algorithm's status.

        Results are pushed to the notification queue and stored in KB every
        *interval_secs* seconds so Niblit's reflection engine can study them.
        """
        key = f"{project_id}:{deploy_id}"
        with self._lock:
            if key in self._monitor_threads and self._monitor_threads[key].is_alive():
                return f"⚠️  Monitor already running for deploy {deploy_id}"

        def _loop() -> None:
            log.info("[LeanDeploy] Monitor started: %s", deploy_id)
            while True:
                try:
                    result = self.read_live_algorithm(project_id, deploy_id)
                    _notif_queue.push(f"[LeanDeploy:monitor] {result[:300]}")
                    # Feed to reflect module if available
                    if self._reflect and hasattr(self._reflect, "reflect_on_trading"):
                        try:
                            self._reflect.reflect_on_lean_live(
                                deploy_id=deploy_id,
                                status_text=result,
                            )
                        except Exception:
                            pass
                except Exception as exc:
                    log.warning("[LeanDeploy:monitor] %s", exc)
                time.sleep(interval_secs)

        t = threading.Thread(
            target=_loop, daemon=True,
            name=f"LeanDeployMonitor:{deploy_id}"
        )
        t.start()
        with self._lock:
            self._monitor_threads[key] = t
        return f"✅ Monitor started for deploy {deploy_id} (interval={interval_secs}s)"

    def stop_monitor(self, deploy_id: str) -> str:
        """Stop the background monitor for a given deploy_id."""
        with self._lock:
            for k in list(self._monitor_threads.keys()):
                if deploy_id in k:
                    # Daemon threads cannot be stopped cleanly; just remove reference
                    del self._monitor_threads[k]
                    return f"✅ Monitor reference removed for {deploy_id}"
        return f"No active monitor for {deploy_id}"

    # ── quick-deploy helpers ──────────────────────────────────────────────────

    def quick_deploy(
        self,
        template: str = "ema_crossover",
        name: str = "NiblitQuickDeploy",
        brokerage: str = "PaperBrokerage",
        brokerage_settings: Optional[Dict[str, Any]] = None,
        **params: Any,
    ) -> str:
        """One-shot: generate algorithm → create project → upload → compile → deploy live.

        Returns a summary string with IDs.
        """
        if not self._has_credentials():
            return self._creds_error()

        # 1. Generate source code
        source = self.generate_algorithm(template=template, name=name, **params)
        if source.startswith("[LeanDeploy]"):
            return source

        # 2. Create cloud project
        create_resp = self._api("POST", "projects/create",
                                {"name": name, "language": "Py"})
        project_id = create_resp.get("projects", [{}])[0].get("projectId")
        if not project_id:
            return f"[LeanDeploy] Could not create project: {create_resp}"

        # 3. Upload source
        self.update_project_files(
            project_id,
            [{"name": "main.py", "content": source}],
        )

        # 4. Compile
        compile_result = self.compile_project(project_id)
        if "error" in compile_result.lower() or "BuildError" in compile_result:
            return f"[LeanDeploy] Compile failed:\n{compile_result}"

        # 5. Get compile ID (read project files to get latest compile)
        # QC API compile/create returns compileId — capture from compile_project
        # We re-run compile to capture the ID
        compile_data = self._api("POST", "compile/create", {"projectId": project_id})
        compile_id = compile_data.get("compileId", "")

        # 6. Deploy live
        deploy_result = self.create_live_algorithm(
            project_id=project_id,
            compile_id=compile_id,
            brokerage=brokerage,
            brokerage_settings=brokerage_settings,
        )
        return (
            f"Quick deploy summary:\n"
            f"  Template:    {template}\n"
            f"  Name:        {name}\n"
            f"  ProjectId:   {project_id}\n"
            f"  Brokerage:   {brokerage}\n"
            f"  Deploy:      {deploy_result}"
        )

    # ── KB helper ─────────────────────────────────────────────────────────────

    def _store_in_kb(
        self,
        key: str,
        text: str,
        tags: Optional[List[str]] = None,
    ) -> None:
        if self._kb is None:
            return
        try:
            self._kb.store(key, text, tags=tags or ["lean", "quantconnect"])
        except Exception:
            pass


# ─────────────────────────────────────────────────────────────────────────────
# Singleton
# ─────────────────────────────────────────────────────────────────────────────

_lean_deploy_engine: Optional[LeanDeployEngine] = None


def get_lean_deploy_engine(
    knowledge_db: Optional[Any] = None,
    reflect_module: Optional[Any] = None,
) -> LeanDeployEngine:
    """Return the global :class:`LeanDeployEngine` singleton."""
    global _lean_deploy_engine
    if _lean_deploy_engine is None:
        _lean_deploy_engine = LeanDeployEngine(
            knowledge_db=knowledge_db,
            reflect_module=reflect_module,
        )
    else:
        if knowledge_db is not None and _lean_deploy_engine._kb is None:
            _lean_deploy_engine._kb = knowledge_db
        if reflect_module is not None and _lean_deploy_engine._reflect is None:
            _lean_deploy_engine._reflect = reflect_module
    return _lean_deploy_engine
