#!/usr/bin/env python3
"""
modules/lean_engine.py — LEAN CLI / QuantConnect integration for Niblit.

Provides :class:`LeanEngine`, a non-blocking wrapper around the LEAN CLI
(QuantConnect/LEAN open-source engine) that lets Niblit's trading brain
create, back-test, and live-trade algorithmic strategies via cloud or local
LEAN installations — all from the Niblit shell or as autonomous background
tasks.

Features
--------
* **Project management** — create / list / delete LEAN algorithm projects.
* **Local back-test** — run ``lean backtest`` in a daemon subprocess, stream
  results to :data:`~core.notification_queue.notif_queue` so they never
  interrupt the Niblit shell.
* **Cloud back-test / live** — run ``lean cloud backtest`` or
  ``lean cloud live``; credentials managed via environment / ParameterManager.
* **Parameter sweeping** — run a grid of back-tests over named parameters and
  store the best-performing set to a JSON file.
* **Parameter store** — persist optimal parameter sets in
  ``niblit_lean_params.json`` (alongside niblit_params.json).
* **Niblit-brain integration** — results / insights are stored in KnowledgeDB
  and pushed to the notification queue; the TradingBrain can retrieve them
  via RAG at decision time.

All LEAN subprocesses run in daemon threads and **never** print directly to
stdout/stderr — output is captured and pushed to the notification queue.

Dependencies
------------
* ``lean`` CLI must be installed (``pip install lean`` or ``pipx install lean``)
  for local / cloud operations.  If not installed, methods degrade gracefully
  and return a clear error message.
* Optional: ``requests`` for downloading sample configs.

Environment variables
---------------------
LEAN_API_USER_ID  — QuantConnect user ID for cloud operations.
LEAN_API_TOKEN    — QuantConnect API token for cloud operations.
LEAN_WORKSPACE    — Root directory for LEAN projects (default: ./lean_workspace).
"""

from __future__ import annotations

import json
import logging
import os
import re
import shutil
import subprocess
import tempfile
import threading
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

log = logging.getLogger("LeanEngine")

# ── notification queue (non-blocking output) ─────────────────────────────────
try:
    from core.notification_queue import notif_queue as _notif_queue
except ImportError:
    class _NopQueue:  # type: ignore[no-redef]
        def push(self, msg: str) -> None:
            pass
    _notif_queue = _NopQueue()  # type: ignore[assignment]

# ── parameter manager (optional) ─────────────────────────────────────────────
try:
    from modules.parameter_manager import parameter_manager as _pm
except ImportError:
    _pm = None  # type: ignore[assignment]

# ── default paths ─────────────────────────────────────────────────────────────
_REPO_ROOT = Path(__file__).resolve().parent.parent
# Use /tmp as fallback when the repo root is read-only (e.g. Vercel Lambda).
_WRITABLE_ROOT = _REPO_ROOT if os.access(str(_REPO_ROOT), os.W_OK) else Path(tempfile.gettempdir())
_DEFAULT_WORKSPACE = _WRITABLE_ROOT / "lean_workspace"
_PARAMS_FILE = _WRITABLE_ROOT / "niblit_lean_params.json"

# ── configurable timeouts ─────────────────────────────────────────────────────
# Override via env var LEAN_BACKTEST_TIMEOUT_SECS or ParameterManager key.
_DEFAULT_BACKTEST_TIMEOUT_SECS: int = int(
    os.environ.get("LEAN_BACKTEST_TIMEOUT_SECS", "3600")
)
# Live sessions may run indefinitely; default is 24 h but 0 = no timeout.
_DEFAULT_LIVE_TIMEOUT_SECS: int = int(
    os.environ.get("LEAN_LIVE_TIMEOUT_SECS", "86400")
)
# Sweep per-iteration timeout (seconds per single backtest in a grid sweep).
_DEFAULT_SWEEP_ITER_TIMEOUT_SECS: int = int(
    os.environ.get("LEAN_SWEEP_ITER_TIMEOUT_SECS", "900")
)

# ── Template for a minimal LEAN algorithm (Python) ───────────────────────────
_ALGO_TEMPLATE = '''# LEAN Algorithm generated by Niblit LeanEngine
# Project: {project_name}

from AlgorithmImports import *


class {class_name}(QCAlgorithm):
    """Niblit-generated LEAN algorithm for {project_name}."""

    def Initialize(self):
        self.SetStartDate({start_year}, {start_month}, {start_day})
        self.SetEndDate({end_year}, {end_month}, {end_day})
        self.SetCash({initial_cash})
        self.AddEquity("{symbol}", Resolution.Daily)
        self.fast = self.EMA("{symbol}", {fast_period}, Resolution.Daily)
        self.slow = self.EMA("{symbol}", {slow_period}, Resolution.Daily)

    def OnData(self, data):
        if not self.fast.IsReady or not self.slow.IsReady:
            return
        holdings = self.Portfolio["{symbol}"].Quantity
        if self.fast.Current.Value > self.slow.Current.Value and holdings <= 0:
            self.SetHoldings("{symbol}", 1)
        elif self.fast.Current.Value < self.slow.Current.Value and holdings > 0:
            self.Liquidate("{symbol}")
'''


def _lean_available() -> bool:
    """Return True if the ``lean`` CLI is on PATH."""
    return shutil.which("lean") is not None


def _to_class_name(name: str) -> str:
    """Convert a project name like 'my-strategy' → 'MyStrategy'."""
    return "".join(word.capitalize() for word in re.split(r"[-_ ]+", name))


# ─────────────────────────────────────────────────────────────────────────────
# LeanEngine
# ─────────────────────────────────────────────────────────────────────────────

class LeanEngine:
    """Non-blocking LEAN CLI wrapper for Niblit.

    Parameters
    ----------
    workspace:
        Root directory for LEAN projects.  Defaults to
        ``<repo_root>/lean_workspace``.
    knowledge_db:
        Optional KnowledgeDB instance to store back-test results/insights.
    """

    def __init__(
        self,
        workspace: Optional[str] = None,
        knowledge_db: Optional[Any] = None,
    ) -> None:
        self.workspace = Path(
            workspace
            or (
                (_pm.get("LEAN_WORKSPACE") if _pm else None)
                or os.environ.get("LEAN_WORKSPACE")
                or str(_DEFAULT_WORKSPACE)
            )
        )
        self._kb = knowledge_db
        self._params_file = _PARAMS_FILE
        self._running_jobs: List[threading.Thread] = []
        self._lock = threading.Lock()
        # Ensure workspace exists
        self.workspace.mkdir(parents=True, exist_ok=True)
        log.info("[LeanEngine] workspace=%s", self.workspace)

    # ── status ─────────────────────────────────────────────────────────────

    def status(self) -> str:
        """Return a human-readable status string."""
        lean_ok = "✅ installed" if _lean_available() else "⚠️  NOT installed (pip install lean)"
        projects = self.list_projects()
        active = sum(1 for t in self._running_jobs if t.is_alive())
        params = self._load_optimal_params()
        return (
            f"LEAN CLI: {lean_ok}\n"
            f"Workspace: {self.workspace}\n"
            f"Projects: {len(projects)} — {[p['name'] for p in projects[:5]]}\n"
            f"Active LEAN jobs: {active}\n"
            f"Stored optimal params: {list(params.keys())[:5] or '(none)'}"
        )

    # ── project management ──────────────────────────────────────────────────

    def create_project(
        self,
        name: str,
        symbol: str = "SPY",
        initial_cash: int = 100_000,
        start: str = "2020-01-01",
        end: str = "2023-12-31",
        fast_period: int = 10,
        slow_period: int = 30,
    ) -> str:
        """Create a new LEAN project directory with a stub algorithm.

        Parameters
        ----------
        name:         Project name (used as folder name and class name).
        symbol:       Primary asset ticker, e.g. ``"SPY"``.
        initial_cash: Starting cash for back-tests.
        start / end:  ISO-8601 date strings for the back-test window.
        fast_period:  Fast EMA window.
        slow_period:  Slow EMA window.

        Returns a human-readable result string.
        """
        proj_dir = self.workspace / name
        if proj_dir.exists():
            return f"[lean create-project] ⚠️  Project '{name}' already exists at {proj_dir}"

        try:
            # Parse dates
            sy, sm, sd = start.split("-")
            ey, em, ed = end.split("-")
        except ValueError:
            sy, sm, sd = "2020", "01", "01"
            ey, em, ed = "2023", "12", "31"

        class_name = _to_class_name(name)
        algo_code = _ALGO_TEMPLATE.format(
            project_name=name,
            class_name=class_name,
            symbol=symbol.upper(),
            initial_cash=initial_cash,
            start_year=sy, start_month=sm, start_day=sd,
            end_year=ey, end_month=em, end_day=ed,
            fast_period=fast_period,
            slow_period=slow_period,
        )

        proj_dir.mkdir(parents=True, exist_ok=True)
        algo_file = proj_dir / f"{class_name}.py"
        algo_file.write_text(algo_code, encoding="utf-8")

        # Write a minimal config.json for the project
        config = {
            "algorithm-language": "Python",
            "parameters": {
                "fast-period": fast_period,
                "slow-period": slow_period,
                "symbol": symbol.upper(),
            },
            "description": f"Niblit-generated strategy for {symbol}",
        }
        (proj_dir / "config.json").write_text(json.dumps(config, indent=2), encoding="utf-8")

        msg = f"✅ LEAN project '{name}' created at {proj_dir} (symbol={symbol})"
        _notif_queue.push(msg)
        log.info("[LeanEngine] %s", msg)
        return msg

    def list_projects(self) -> List[Dict[str, Any]]:
        """Return a list of project dicts ``{name, path, has_config}``."""
        projects = []
        if not self.workspace.exists():
            return projects
        for item in sorted(self.workspace.iterdir()):
            if item.is_dir():
                projects.append({
                    "name": item.name,
                    "path": str(item),
                    "has_config": (item / "config.json").exists(),
                })
        return projects

    def delete_project(self, name: str) -> str:
        """Delete a LEAN project directory."""
        proj_dir = self.workspace / name
        if not proj_dir.exists():
            return f"[lean delete-project] Project '{name}' not found"
        shutil.rmtree(proj_dir, ignore_errors=True)
        msg = f"✅ LEAN project '{name}' deleted"
        _notif_queue.push(msg)
        return msg

    # ── back-test ───────────────────────────────────────────────────────────

    def run_backtest(
        self,
        project_name: str,
        extra_args: Optional[List[str]] = None,
        cloud: bool = False,
    ) -> str:
        """Launch a LEAN back-test in a background daemon thread.

        The back-test runs asynchronously; results are pushed to the
        notification queue when done.  This method returns immediately so
        the Niblit shell is never blocked.

        Parameters
        ----------
        project_name: Name of the project folder in the workspace.
        extra_args:   Additional ``lean`` CLI arguments.
        cloud:        If True, run ``lean cloud backtest``.

        Returns a startup status string.
        """
        if not _lean_available():
            return (
                "[lean backtest] LEAN CLI not installed.\n"
                "Install with:  pip install lean\n"
                "Then authenticate: lean login"
            )

        proj_dir = self.workspace / project_name
        if not proj_dir.exists() and not cloud:
            return f"[lean backtest] Project '{project_name}' not found at {proj_dir}"

        def _run() -> None:
            if cloud:
                cmd = ["lean", "cloud", "backtest", project_name] + (extra_args or [])
            else:
                cmd = ["lean", "backtest", str(proj_dir)] + (extra_args or [])

            _notif_queue.push(f"[LeanEngine] Starting {'cloud ' if cloud else ''}backtest: {project_name}")
            log.info("[LeanEngine] Running: %s", " ".join(cmd))
            try:
                env = {**os.environ}
                uid = (
                    (_pm.get("LEAN_API_USER_ID") if _pm else None)
                    or os.environ.get("LEAN_API_USER_ID", "")
                )
                token = (
                    (_pm.get("LEAN_API_TOKEN") if _pm else None)
                    or os.environ.get("LEAN_API_TOKEN", "")
                )
                if uid:
                    env["LEAN_API_USER_ID"] = uid
                if token:
                    env["LEAN_API_TOKEN"] = token

                result = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    env=env,
                    timeout=_DEFAULT_BACKTEST_TIMEOUT_SECS,
                )
                output = (result.stdout or "") + (result.stderr or "")
                success = result.returncode == 0
                status_tag = "✅" if success else "❌"
                summary = (
                    f"[LeanEngine] {status_tag} Backtest '{project_name}' "
                    f"finished (rc={result.returncode})"
                )
                _notif_queue.push(summary)
                # Store a snippet in KnowledgeDB for future RAG context
                if self._kb is not None:
                    snippet = output[:800] if output else "(no output)"
                    key = f"lean_backtest:{project_name}:{int(time.time())}"
                    try:
                        self._kb.store(
                            key,
                            f"LEAN backtest '{project_name}' result: {snippet}",
                            tags=["lean", "backtest", "trading"],
                        )
                    except Exception:
                        pass
                # Extract and save any performance metrics found in output
                self._extract_and_store_metrics(project_name, output)
            except subprocess.TimeoutExpired:
                _notif_queue.push(
                    f"[LeanEngine] ⏱️  Backtest '{project_name}' timed out "
                    f"({_DEFAULT_BACKTEST_TIMEOUT_SECS}s)"
                )
            except Exception as exc:
                _notif_queue.push(f"[LeanEngine] Backtest error: {exc}")
                log.warning("[LeanEngine] Backtest subprocess error: %s", exc)

        t = threading.Thread(target=_run, daemon=True, name=f"LeanBacktest:{project_name}")
        t.start()
        with self._lock:
            self._running_jobs.append(t)
        return (
            f"⏳ LEAN {'cloud ' if cloud else ''}backtest for '{project_name}' started in background.\n"
            "Use 'notifications' to see results when done."
        )

    def run_live(self, project_name: str, broker: str = "paper") -> str:
        """Launch a LEAN live-trading session in a background daemon thread.

        Parameters
        ----------
        project_name: LEAN project name.
        broker:       Broker name or ``'paper'`` for paper trading.
        """
        if not _lean_available():
            return "[lean live] LEAN CLI not installed (pip install lean)"
        msg = (
            f"⏳ LEAN live trading for '{project_name}' (broker={broker}) "
            "started in background.\nUse 'notifications' for updates."
        )

        def _run() -> None:
            cmd = ["lean", "cloud", "live", project_name, "--brokerage", broker]
            _notif_queue.push(f"[LeanEngine] Starting live: {project_name} (broker={broker})")
            try:
                env = {**os.environ}
                uid = (
                    (_pm.get("LEAN_API_USER_ID") if _pm else None)
                    or os.environ.get("LEAN_API_USER_ID", "")
                )
                token = (
                    (_pm.get("LEAN_API_TOKEN") if _pm else None)
                    or os.environ.get("LEAN_API_TOKEN", "")
                )
                if uid:
                    env["LEAN_API_USER_ID"] = uid
                if token:
                    env["LEAN_API_TOKEN"] = token
                subprocess.run(cmd, capture_output=True, text=True, env=env,
                               timeout=_DEFAULT_LIVE_TIMEOUT_SECS or None)
                _notif_queue.push(f"[LeanEngine] Live session ended: {project_name}")
            except Exception as exc:
                _notif_queue.push(f"[LeanEngine] Live error: {exc}")

        t = threading.Thread(target=_run, daemon=True, name=f"LeanLive:{project_name}")
        t.start()
        with self._lock:
            self._running_jobs.append(t)
        return msg

    # ── parameter sweep ─────────────────────────────────────────────────────

    def parameter_sweep(
        self,
        project_name: str,
        param_grid: Dict[str, List[Any]],
        metric: str = "Sharpe Ratio",
    ) -> str:
        """Run a grid search over back-test parameters in the background.

        Parameters
        ----------
        project_name: LEAN project to optimise.
        param_grid:   ``{param_name: [value1, value2, …]}``.
        metric:       Performance metric to maximise (parsed from LEAN output).

        Results are stored in ``niblit_lean_params.json`` and pushed as
        notifications.
        """
        if not _lean_available():
            return "[lean sweep] LEAN CLI not installed (pip install lean)"

        # Build combinations
        import itertools
        keys = list(param_grid.keys())
        values = [param_grid[k] for k in keys]
        combos = list(itertools.product(*values))

        def _run_sweep() -> None:
            _notif_queue.push(
                f"[LeanEngine] Parameter sweep starting: {len(combos)} combinations"
            )
            best_value: Optional[float] = None
            best_params: Optional[Dict[str, Any]] = None

            for combo in combos:
                params = dict(zip(keys, combo))
                # Update project config
                proj_dir = self.workspace / project_name
                config_path = proj_dir / "config.json"
                try:
                    if config_path.exists():
                        cfg = json.loads(config_path.read_text(encoding="utf-8"))
                    else:
                        cfg = {}
                    cfg.setdefault("parameters", {}).update(params)
                    config_path.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
                except Exception as cfg_exc:
                    log.debug("[LeanEngine] Config update failed: %s", cfg_exc)

                # Run backtest synchronously within this thread
                cmd = ["lean", "backtest", str(proj_dir)]
                try:
                    result = subprocess.run(
                        cmd, capture_output=True, text=True, timeout=_DEFAULT_SWEEP_ITER_TIMEOUT_SECS
                    )
                    output = result.stdout or ""
                    metric_val = self._parse_metric(output, metric)
                    if metric_val is not None:
                        if best_value is None or metric_val > best_value:
                            best_value = metric_val
                            best_params = dict(params)
                            _notif_queue.push(
                                f"[LeanEngine] New best {metric}={metric_val:.4f} "
                                f"params={params}"
                            )
                except Exception as exc:
                    log.debug("[LeanEngine] Sweep iteration error: %s", exc)

            if best_params:
                self._save_optimal_params(project_name, best_params, best_value, metric)
                _notif_queue.push(
                    f"[LeanEngine] Sweep done. Best {metric}={best_value:.4f}: {best_params}"
                )
            else:
                _notif_queue.push("[LeanEngine] Sweep complete — no metric found in outputs")

        t = threading.Thread(target=_run_sweep, daemon=True, name=f"LeanSweep:{project_name}")
        t.start()
        with self._lock:
            self._running_jobs.append(t)
        return (
            f"⏳ Parameter sweep for '{project_name}' started "
            f"({len(combos)} combos, metric={metric}).\n"
            "Use 'notifications' for updates."
        )

    # ── optimal parameters ──────────────────────────────────────────────────

    def _load_optimal_params(self) -> Dict[str, Any]:
        """Load stored optimal parameter sets from the JSON file."""
        try:
            if self._params_file.exists():
                return json.loads(self._params_file.read_text(encoding="utf-8"))
        except Exception:
            pass
        return {}

    def _save_optimal_params(
        self,
        project_name: str,
        params: Dict[str, Any],
        score: Optional[float],
        metric: str,
    ) -> None:
        """Persist an optimal parameter set for a project."""
        data = self._load_optimal_params()
        data[project_name] = {
            "params": params,
            "score": score,
            "metric": metric,
            "timestamp": int(time.time()),
        }
        try:
            self._params_file.write_text(json.dumps(data, indent=2), encoding="utf-8")
        except Exception as exc:
            log.warning("[LeanEngine] Failed to save optimal params: %s", exc)

    def get_optimal_params(self, project_name: str) -> Optional[Dict[str, Any]]:
        """Return the stored optimal parameters for a project, or None."""
        return self._load_optimal_params().get(project_name)

    # ── helpers ─────────────────────────────────────────────────────────────

    @staticmethod
    def _parse_metric(output: str, metric: str) -> Optional[float]:
        """Attempt to extract a numeric metric from LEAN CLI output text."""
        pattern = re.compile(
            rf"{re.escape(metric)}[:\s]+([0-9]+\.?[0-9]*)",
            re.IGNORECASE,
        )
        m = pattern.search(output)
        if m:
            try:
                return float(m.group(1))
            except ValueError:
                pass
        return None

    def _extract_and_store_metrics(self, project_name: str, output: str) -> None:
        """Parse common LEAN performance metrics and store them for RAG."""
        if self._kb is None or not output:
            return
        metrics: Dict[str, Optional[float]] = {}
        for m_name in ("Sharpe Ratio", "Net Profit", "Drawdown", "Win Rate"):
            val = self._parse_metric(output, m_name)
            if val is not None:
                metrics[m_name] = val
        if metrics:
            key = f"lean_metrics:{project_name}:{int(time.time())}"
            try:
                self._kb.store(
                    key,
                    f"LEAN strategy '{project_name}' metrics: " + ", ".join(
                        f"{k}={v}" for k, v in metrics.items()
                    ),
                    tags=["lean", "metrics", "trading"],
                )
            except Exception:
                pass

    # ── login / cloud helpers ───────────────────────────────────────────────

    def login(self, user_id: str = "", api_token: str = "") -> str:
        """Authenticate with QuantConnect cloud using ``lean login``.

        If *user_id* / *api_token* are empty, reads from env vars /
        ParameterManager.
        """
        if not _lean_available():
            return "[lean login] LEAN CLI not installed"
        uid = user_id or (_pm.get("LEAN_API_USER_ID") if _pm else "") or os.environ.get("LEAN_API_USER_ID", "")
        token = api_token or (_pm.get("LEAN_API_TOKEN") if _pm else "") or os.environ.get("LEAN_API_TOKEN", "")
        if not uid or not token:
            return (
                "[lean login] Set LEAN_API_USER_ID and LEAN_API_TOKEN in your "
                "environment or niblit_params.json, then run 'lean login' again."
            )
        try:
            result = subprocess.run(
                ["lean", "login", "--user-id", uid, "--api-token", token],
                capture_output=True, text=True, timeout=30,
            )
            out = (result.stdout or "") + (result.stderr or "")
            if result.returncode == 0:
                return "✅ LEAN cloud login successful"
            return f"[lean login] Failed (rc={result.returncode}): {out[:300]}"
        except Exception as exc:
            return f"[lean login] Error: {exc}"

    def active_jobs_summary(self) -> str:
        """Return a summary of currently running LEAN jobs."""
        with self._lock:
            alive = [t.name for t in self._running_jobs if t.is_alive()]
        if not alive:
            return "No active LEAN jobs."
        return "Active LEAN jobs:\n" + "\n".join(f"  • {n}" for n in alive)


# ─────────────────────────────────────────────────────────────────────────────
# Module-level singleton (instantiated lazily on first import)
# ─────────────────────────────────────────────────────────────────────────────

#: Global LeanEngine singleton.  Import and use this in niblit_core / router.
lean_engine: Optional[LeanEngine] = None


def get_lean_engine(knowledge_db: Optional[Any] = None) -> LeanEngine:
    """Return the global :class:`LeanEngine`, creating it on first call."""
    global lean_engine
    if lean_engine is None:
        lean_engine = LeanEngine(knowledge_db=knowledge_db)
    elif knowledge_db is not None and lean_engine._kb is None:
        lean_engine._kb = knowledge_db
    return lean_engine
