#!/usr/bin/env python3
"""
modules/llm_architect_engine.py — LLM Architecture Engine for Niblit
=====================================================================
Implements the same pipeline that ML engineers use to build production LLMs,
applied to Niblit's continuous self-improvement loop.

The four-stage pipeline mirrors real LLM development:

  Stage 1 — DATA CURATION
    Collect, deduplicate, filter, and format training corpora from:
    - Niblit's own KB (facts, research findings, reflections, chat logs)
    - GitHub research findings from Nibblebots
    - Code files generated by ALE
    The result is a JSONL dataset of (prompt, completion) pairs.

  Stage 2 — SUPERVISED FINE-TUNING (SFT)
    Use the curated dataset to update the brain's in-context knowledge
    via BrainTrainer.  When a full local model is available (LOCAL_MODEL_PATH),
    this dispatches a LoRA/QLoRA fine-tuning job via the `trl` + `peft`
    libraries if they are installed, otherwise queues the data for the
    next manual fine-tune run.

  Stage 3 — RLHF / PREFERENCE OPTIMIZATION (DPO / PPO)
    Treat every KB fact quality score (reward_model.py) as an implicit
    preference signal.  Positive scores → "chosen" examples; negative/zero
    scores → "rejected" examples.  These preference pairs feed the DPO
    trainer when `trl` is available.

  Stage 4 — EVALUATION
    After each SFT or DPO step, run an evaluation pass:
    - Perplexity proxy: compare LLM completions against KB ground truth
    - Held-out QA accuracy: structured Q/A pairs from LLMTrainingAgent
    - Win-rate: compare new-vs-old completions via reward model
    Results are stored in KnowledgeDB as ``ale_llm_eval:<ts>`` facts.

This engine is:
 - Wired into ALE as Step 32 ("LLMArchitectCycle"), throttled every 10 cycles.
 - Callable via CLI: ``niblit llm-architect status | run | eval``
 - A singleton via ``get_llm_architect_engine()``.

Design notes
------------
* All heavy imports (trl, peft, torch, datasets, evaluate) are lazy so
  Niblit starts instantly on machines without a GPU.  Each feature degrades
  gracefully when its dependency is absent.
* The engine never overwrites the currently-running HFBrain model; it only
  writes fine-tuned checkpoints to NIBLIT_FINETUNE_OUTPUT_DIR.
* Thread-safe: a single threading.Lock guards the dataset write path.
"""

from __future__ import annotations

import json
import logging
import os
import threading
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

log = logging.getLogger(__name__)

# ── Optional heavy imports (graceful degradation) ────────────────────────────
_TRL_AVAILABLE = False
_PEFT_AVAILABLE = False
_TORCH_AVAILABLE = False
_DATASETS_AVAILABLE = False
_EVALUATE_AVAILABLE = False

try:
    import torch  # noqa: F401
    _TORCH_AVAILABLE = True
except ImportError:
    pass

try:
    from datasets import Dataset  # noqa: F401
    _DATASETS_AVAILABLE = True
except ImportError:
    pass

try:
    from trl import SFTTrainer, DPOTrainer  # noqa: F401
    _TRL_AVAILABLE = True
except ImportError:
    pass

try:
    from peft import LoraConfig, get_peft_model, TaskType  # noqa: F401
    _PEFT_AVAILABLE = True
except ImportError:
    pass

try:
    import evaluate  # noqa: F401
    _EVALUATE_AVAILABLE = True
except ImportError:
    pass

# lm-eval-harness availability check (lazy — heavy import only inside method)
_LM_EVAL_AVAILABLE = False
try:
    import lm_eval  # noqa: F401
    _LM_EVAL_AVAILABLE = True
except ImportError:
    pass

# ── Paths ─────────────────────────────────────────────────────────────────────
def _writable_path(filename: str, env_var: str = "") -> Path:
    if env_var:
        candidate = os.environ.get(env_var, "")
        if candidate:
            return Path(candidate)
    for candidate in [Path.cwd(), Path(os.path.expanduser("~"))]:
        if os.access(candidate, os.W_OK):
            return candidate / filename
    import tempfile
    return Path(tempfile.gettempdir()) / filename

_DATASET_PATH = _writable_path("niblit_sft_dataset.jsonl", "NIBLIT_SFT_DATASET_PATH")
_PREF_DATASET_PATH = _writable_path("niblit_dpo_dataset.jsonl", "NIBLIT_DPO_DATASET_PATH")
_FINETUNE_OUTPUT_DIR = _writable_path("niblit_finetuned", "NIBLIT_FINETUNE_OUTPUT_DIR")
_EVAL_LOG_PATH = _writable_path("niblit_eval_log.jsonl", "NIBLIT_EVAL_LOG_PATH")


class LLMArchitectEngine:
    """
    Implements the LLM engineer's pipeline as a continuous background process
    for Niblit: data curation → SFT → DPO/RLHF → evaluation.

    Parameters
    ----------
    knowledge_db : optional
        KnowledgeDB instance for reading facts and writing eval results.
    brain_trainer : optional
        BrainTrainer instance used for SFT record storage.
    hf_brain : optional
        HFBrain instance used for evaluation completions.
    reward_model : optional
        RewardModel instance for preference signal extraction.
    llm_training_agent : optional
        LLMTrainingAgent for gap-based training data generation.
    """

    # How many KB facts to collect per curation run
    _MAX_FACTS_PER_CURATION: int = 200
    # Minimum quality score threshold for "chosen" examples in DPO
    _DPO_CHOSEN_THRESHOLD: float = 0.6
    # Max SFT records per fine-tune batch (avoids OOM on small devices)
    _SFT_BATCH_MAX: int = 500
    # Max eval Q/A pairs per evaluation pass
    _EVAL_MAX_QA: int = 20
    # lm-eval tasks to run when lm-eval-harness is available
    _LM_EVAL_TASKS: List[str] = ["hellaswag", "mmlu"]
    # Max number of few-shot examples for lm-eval tasks
    _LM_EVAL_NUM_FEWSHOT: int = 0

    def __init__(
        self,
        knowledge_db=None,
        brain_trainer=None,
        hf_brain=None,
        reward_model=None,
        llm_training_agent=None,
    ):
        self.knowledge_db = knowledge_db
        self.brain_trainer = brain_trainer
        self.hf_brain = hf_brain
        self.reward_model = reward_model
        self.llm_training_agent = llm_training_agent

        self._lock = threading.Lock()
        self._stats: Dict[str, Any] = {
            "curation_runs": 0,
            "sft_records_written": 0,
            "dpo_pairs_written": 0,
            "eval_passes": 0,
            "lm_eval_passes": 0,
            "last_run_ts": None,
        }

        log.info(
            "[LLMArchitect] Initialised — torch=%s trl=%s peft=%s datasets=%s "
            "evaluate=%s lm_eval=%s",
            _TORCH_AVAILABLE, _TRL_AVAILABLE, _PEFT_AVAILABLE,
            _DATASETS_AVAILABLE, _EVALUATE_AVAILABLE, _LM_EVAL_AVAILABLE,
        )

    # ─────────────────────────────────────────────────────────────────────────
    # Stage 1 — Data Curation
    # ─────────────────────────────────────────────────────────────────────────

    def _curate_sft_records(self) -> List[Dict[str, str]]:
        """Extract (prompt, completion) pairs from the KB.

        Sources prioritised by quality:
          1. ``ale_llm_train:*`` records (structured Q/A from LLMTrainingAgent)
          2. ``ale_reflection:*`` records (Niblit's own reflections)
          3. ``topic_knowledge:*`` records (concept summaries)
          4. ``ale_research:*`` records (raw research findings)
        """
        records: List[Dict[str, str]] = []
        if self.knowledge_db is None:
            return records

        prefixes = [
            "ale_llm_train:",
            "ale_reflection:",
            "topic_knowledge:",
            "ale_research:",
        ]
        seen: set = set()

        for prefix in prefixes:
            try:
                facts = self.knowledge_db.list_facts(self._MAX_FACTS_PER_CURATION)
            except Exception:
                facts = []

            for f in facts:
                key = f.get("key", "")
                val = f.get("value", "")
                if not key.startswith(prefix):
                    continue
                if key in seen:
                    continue
                seen.add(key)

                # Build prompt/completion pair
                if isinstance(val, dict):
                    prompt = val.get("question") or val.get("topic") or key
                    completion = val.get("answer") or val.get("content") or str(val)
                else:
                    prompt = f"What does Niblit know about {key.split(':')[1].replace('_', ' ')}?"
                    completion = str(val)[:1000]

                if prompt and completion and len(completion) > 20:
                    records.append({
                        "prompt": str(prompt)[:512],
                        "completion": str(completion)[:1024],
                        "source": prefix.rstrip(":"),
                    })

            if len(records) >= self._SFT_BATCH_MAX:
                break

        return records[:self._SFT_BATCH_MAX]

    def _curate_dpo_pairs(self) -> List[Dict[str, str]]:
        """Extract (prompt, chosen, rejected) triples using reward scores.

        The reward_model's node scores are the implicit preference signal —
        facts with high scores are "chosen"; lower-quality facts about the
        same topic become "rejected".
        """
        pairs: List[Dict[str, str]] = []
        if self.knowledge_db is None or self.reward_model is None:
            return pairs

        try:
            facts = self.knowledge_db.list_facts(self._MAX_FACTS_PER_CURATION)
        except Exception:
            return pairs

        # Group by topic prefix
        topic_buckets: Dict[str, List[Tuple[float, str]]] = {}
        for f in facts:
            key = f.get("key", "")
            val = f.get("value", "")
            topic = key.split(":")[0] if ":" in key else key
            score = 0.0
            try:
                score = float(self.reward_model.get_score(key))
            except Exception:
                pass
            topic_buckets.setdefault(topic, []).append((score, str(val)[:800]))

        for topic, items in topic_buckets.items():
            if len(items) < 2:
                continue
            items.sort(key=lambda x: x[0], reverse=True)
            best_score, best_text = items[0]
            worst_score, worst_text = items[-1]
            if best_score >= self._DPO_CHOSEN_THRESHOLD and best_text != worst_text:
                pairs.append({
                    "prompt": f"Tell me about {topic.replace('_', ' ')}.",
                    "chosen": best_text,
                    "rejected": worst_text,
                })

        return pairs

    def run_curation(self) -> str:
        """Stage 1: Curate SFT and DPO datasets and write to disk."""
        with self._lock:
            sft_records = self._curate_sft_records()
            dpo_pairs = self._curate_dpo_pairs()

            # Write SFT dataset
            sft_written = 0
            try:
                with open(_DATASET_PATH, "a", encoding="utf-8") as f:
                    for rec in sft_records:
                        f.write(json.dumps(rec, ensure_ascii=False) + "\n")
                        sft_written += 1
            except Exception as exc:
                log.debug("[LLMArchitect] SFT dataset write failed: %s", exc)

            # Write DPO dataset
            dpo_written = 0
            try:
                with open(_PREF_DATASET_PATH, "a", encoding="utf-8") as f:
                    for pair in dpo_pairs:
                        f.write(json.dumps(pair, ensure_ascii=False) + "\n")
                        dpo_written += 1
            except Exception as exc:
                log.debug("[LLMArchitect] DPO dataset write failed: %s", exc)

            self._stats["curation_runs"] += 1
            self._stats["sft_records_written"] += sft_written
            self._stats["dpo_pairs_written"] += dpo_written

        result = (
            f"Curation: +{sft_written} SFT records (total={self._stats['sft_records_written']}), "
            f"+{dpo_written} DPO pairs (total={self._stats['dpo_pairs_written']})"
        )
        log.info("[LLMArchitect] %s", result)
        return result

    # ─────────────────────────────────────────────────────────────────────────
    # Stage 2 — Supervised Fine-Tuning
    # ─────────────────────────────────────────────────────────────────────────

    def run_sft(self) -> str:
        """Stage 2: Supervised fine-tuning.

        When trl + peft are available and LOCAL_MODEL_PATH is set, this runs
        a real LoRA SFT pass.  Otherwise it feeds records into BrainTrainer
        for in-context learning (the degraded but always-working path).
        """
        local_model = os.environ.get("LOCAL_MODEL_PATH", "")

        if _TRL_AVAILABLE and _PEFT_AVAILABLE and _TORCH_AVAILABLE and local_model:
            return self._run_lora_sft(local_model)
        return self._run_brain_trainer_sft()

    def _run_brain_trainer_sft(self) -> str:
        """Fallback SFT via BrainTrainer (no GPU required)."""
        if self.brain_trainer is None:
            return "[SFT] BrainTrainer not available — skipping"

        records = self._curate_sft_records()
        pushed = 0
        for rec in records:
            try:
                self.brain_trainer.record_exchange(
                    question=rec["prompt"],
                    answer=rec["completion"],
                    source=rec.get("source", "llm_architect_sft"),
                )
                pushed += 1
            except Exception as exc:
                log.debug("[LLMArchitect] BrainTrainer push failed: %s", exc)

        result = f"SFT via BrainTrainer: pushed {pushed} records"
        log.info("[LLMArchitect] %s", result)
        return result

    def _run_lora_sft(self, model_path: str) -> str:
        """Full LoRA SFT using trl.SFTTrainer + peft.LoraConfig."""
        try:
            from trl import SFTTrainer, SFTConfig
            from peft import LoraConfig, get_peft_model, TaskType
            from datasets import Dataset
            from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments

            log.info("[LLMArchitect] Starting LoRA SFT on model: %s", model_path)

            records = self._curate_sft_records()
            if not records:
                return "[SFT-LoRA] No training data available"

            tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
            if tokenizer.pad_token is None:
                tokenizer.pad_token = tokenizer.eos_token

            dataset = Dataset.from_list([
                {"text": f"<|user|>{r['prompt']}<|assistant|>{r['completion']}<|end|>"}
                for r in records
            ])

            model = AutoModelForCausalLM.from_pretrained(
                model_path,
                torch_dtype="auto",
                device_map="auto",
                trust_remote_code=True,
            )

            lora_config = LoraConfig(
                task_type=TaskType.CAUSAL_LM,
                r=int(os.environ.get("LORA_R", "8")),
                lora_alpha=int(os.environ.get("LORA_ALPHA", "16")),
                lora_dropout=float(os.environ.get("LORA_DROPOUT", "0.05")),
                target_modules=["q_proj", "v_proj"],
            )
            model = get_peft_model(model, lora_config)

            output_dir = str(_FINETUNE_OUTPUT_DIR / f"sft_{int(time.time())}")
            training_args = TrainingArguments(
                output_dir=output_dir,
                num_train_epochs=int(os.environ.get("SFT_EPOCHS", "1")),
                per_device_train_batch_size=int(os.environ.get("SFT_BATCH_SIZE", "2")),
                gradient_accumulation_steps=4,
                learning_rate=float(os.environ.get("SFT_LR", "2e-4")),
                logging_steps=10,
                save_strategy="no",
                report_to=["none"],
            )

            trainer = SFTTrainer(
                model=model,
                args=training_args,
                train_dataset=dataset,
                tokenizer=tokenizer,
            )
            trainer.train()
            model.save_pretrained(output_dir)
            tokenizer.save_pretrained(output_dir)

            result = f"LoRA SFT complete — checkpoint saved to {output_dir}"
            log.info("[LLMArchitect] %s", result)
            return result

        except Exception as exc:
            log.warning("[LLMArchitect] LoRA SFT failed: %s", exc)
            return self._run_brain_trainer_sft()

    # ─────────────────────────────────────────────────────────────────────────
    # Stage 3 — RLHF / DPO
    # ─────────────────────────────────────────────────────────────────────────

    def run_dpo(self) -> str:
        """Stage 3: DPO preference optimisation.

        Uses reward_model preference scores as the implicit signal.
        Falls back to KB-based quality ranking when trl is absent.
        """
        local_model = os.environ.get("LOCAL_MODEL_PATH", "")

        if _TRL_AVAILABLE and _TORCH_AVAILABLE and local_model:
            return self._run_dpo_trainer(local_model)
        return self._run_kb_preference_update()

    def _run_kb_preference_update(self) -> str:
        """Lightweight DPO proxy: reinforce high-quality KB facts via BrainTrainer."""
        if self.brain_trainer is None or self.knowledge_db is None:
            return "[DPO] BrainTrainer/KnowledgeDB not available — skipping"

        pairs = self._curate_dpo_pairs()
        reinforced = 0
        for pair in pairs:
            try:
                # Push "chosen" as a high-quality training record
                self.brain_trainer.record_exchange(
                    question=pair["prompt"],
                    answer=pair["chosen"],
                    source="llm_architect_dpo_chosen",
                )
                reinforced += 1
            except Exception as exc:
                log.debug("[LLMArchitect] DPO KB update failed: %s", exc)

        result = f"DPO via KB preference update: reinforced {reinforced} pairs"
        log.info("[LLMArchitect] %s", result)
        return result

    def _run_dpo_trainer(self, model_path: str) -> str:
        """Full DPO using trl.DPOTrainer."""
        try:
            from trl import DPOTrainer, DPOConfig
            from datasets import Dataset
            from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments

            pairs = self._curate_dpo_pairs()
            if not pairs:
                return "[DPO-trl] No preference pairs available"

            tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
            if tokenizer.pad_token is None:
                tokenizer.pad_token = tokenizer.eos_token

            model = AutoModelForCausalLM.from_pretrained(
                model_path, torch_dtype="auto", device_map="auto",
                trust_remote_code=True
            )
            ref_model = AutoModelForCausalLM.from_pretrained(
                model_path, torch_dtype="auto", device_map="auto",
                trust_remote_code=True
            )

            dataset = Dataset.from_list(pairs)
            output_dir = str(_FINETUNE_OUTPUT_DIR / f"dpo_{int(time.time())}")

            dpo_config = DPOConfig(
                output_dir=output_dir,
                num_train_epochs=1,
                per_device_train_batch_size=1,
                learning_rate=float(os.environ.get("DPO_LR", "1e-5")),
                beta=float(os.environ.get("DPO_BETA", "0.1")),
                report_to=["none"],
            )

            trainer = DPOTrainer(
                model=model,
                ref_model=ref_model,
                args=dpo_config,
                tokenizer=tokenizer,
                train_dataset=dataset,
            )
            trainer.train()
            model.save_pretrained(output_dir)

            result = f"DPO training complete — checkpoint saved to {output_dir}"
            log.info("[LLMArchitect] %s", result)
            return result

        except Exception as exc:
            log.warning("[LLMArchitect] DPO training failed: %s", exc)
            return self._run_kb_preference_update()

    # ─────────────────────────────────────────────────────────────────────────
    # Stage 4 — Evaluation
    # ─────────────────────────────────────────────────────────────────────────

    def run_eval(self) -> str:
        """Stage 4: Evaluate the current brain against held-out QA pairs.

        Metrics:
          - Hit rate: fraction of KB-grounded answers the LLM gets right
          - Mean answer length: completeness proxy
          - Reward model win rate: new vs. old completion quality
        """
        if self.hf_brain is None:
            return "[Eval] HFBrain not available — skipping"
        if self.knowledge_db is None:
            return "[Eval] KnowledgeDB not available — skipping"

        # Pull evaluation QA pairs from LLMTrainingAgent or KB
        qa_pairs: List[Dict[str, str]] = []
        if self.llm_training_agent is not None:
            try:
                qa_pairs = self.llm_training_agent.get_training_pairs(
                    limit=self._EVAL_MAX_QA
                )
            except Exception:
                pass

        if not qa_pairs:
            # Fallback: build from KB facts
            try:
                facts = self.knowledge_db.list_facts(self._EVAL_MAX_QA)
                for f in facts:
                    k = f.get("key", "")
                    v = f.get("value", "")
                    if isinstance(v, str) and len(v) > 30:
                        qa_pairs.append({
                            "question": f"What does Niblit know about {k.replace('_', ' ')}?",
                            "answer": v[:300],
                        })
            except Exception:
                pass

        if not qa_pairs:
            return "[Eval] No QA pairs available"

        hits = 0
        total = 0
        reward_scores = []

        for pair in qa_pairs[:self._EVAL_MAX_QA]:
            question = pair.get("question") or pair.get("prompt", "")
            ground_truth = pair.get("answer") or pair.get("completion", "")
            if not question or not ground_truth:
                continue

            total += 1
            try:
                # Get LLM completion
                completion = ""
                if hasattr(self.hf_brain, "ask"):
                    completion = self.hf_brain.ask(question) or ""
                elif hasattr(self.hf_brain, "think"):
                    completion = self.hf_brain.think(question) or ""

                # Simple keyword overlap as hit proxy
                gt_words = set(ground_truth.lower().split())
                comp_words = set(completion.lower().split())
                overlap = len(gt_words & comp_words) / max(len(gt_words), 1)
                if overlap > 0.2:
                    hits += 1

                # Reward model score if available
                if self.reward_model is not None:
                    try:
                        score = self.reward_model.score_text(completion)
                        reward_scores.append(score)
                    except Exception:
                        pass

            except Exception as exc:
                log.debug("[LLMArchitect] Eval pair failed: %s", exc)

        hit_rate = hits / max(total, 1)
        avg_reward = sum(reward_scores) / max(len(reward_scores), 1) if reward_scores else None

        eval_record = {
            "ts": int(time.time()),
            "total": total,
            "hits": hits,
            "hit_rate": round(hit_rate, 3),
            "avg_reward_score": round(avg_reward, 3) if avg_reward is not None else None,
        }

        # Persist to KB
        try:
            self.knowledge_db.add_fact(
                f"ale_llm_eval:{eval_record['ts']}",
                eval_record,
                tags=["eval", "llm_architect", "quality"],
            )
        except Exception:
            pass

        # Persist to eval log
        try:
            with open(_EVAL_LOG_PATH, "a") as f:
                f.write(json.dumps(eval_record) + "\n")
        except Exception:
            pass

        self._stats["eval_passes"] += 1

        result = (
            f"Eval: {hits}/{total} hits ({hit_rate:.1%} hit rate)"
            + (f", avg_reward={avg_reward:.3f}" if avg_reward is not None else "")
        )
        log.info("[LLMArchitect] %s", result)
        return result

    # ─────────────────────────────────────────────────────────────────────────
    # Stage 4b — lm-eval-harness Evaluation
    # ─────────────────────────────────────────────────────────────────────────

    def run_lm_eval_harness(self, model_path: str = "") -> str:
        """Run lm-eval-harness benchmarks on a local model checkpoint.

        When ``lm_eval`` is installed and a model path is provided (either via
        *model_path* or the ``LOCAL_MODEL_PATH`` environment variable), this
        method evaluates the model on :attr:`_LM_EVAL_TASKS` and persists the
        results to the KB as ``ale_lm_eval:<ts>`` facts.

        Falls back gracefully when:
          * ``lm_eval`` is not installed
          * No local model path is configured
          * Evaluation fails for any reason

        Args:
            model_path: Path to a HuggingFace-compatible local checkpoint.
                        Defaults to ``LOCAL_MODEL_PATH`` env var.

        Returns:
            Human-readable status string with per-task accuracy scores.
        """
        resolved_path = model_path or os.environ.get("LOCAL_MODEL_PATH", "")
        if not resolved_path:
            return "[lm-eval] No local model path set — skipping (set LOCAL_MODEL_PATH)"

        if not _LM_EVAL_AVAILABLE:
            return (
                "[lm-eval] lm-eval-harness not installed — skipping. "
                "Install with: pip install lm-eval"
            )

        log.info(
            "[LLMArchitect] Running lm-eval-harness on %s — tasks=%s",
            resolved_path, self._LM_EVAL_TASKS,
        )

        try:
            import lm_eval as _lm_eval  # noqa: F401

            # lm_eval ≥ 0.4 API
            results = _lm_eval.simple_evaluate(
                model="hf",
                model_args=f"pretrained={resolved_path},trust_remote_code=True",
                tasks=self._LM_EVAL_TASKS,
                num_fewshot=self._LM_EVAL_NUM_FEWSHOT,
                batch_size="auto",
                log_samples=False,
            )

            task_scores: Dict[str, Any] = {}
            if isinstance(results, dict) and "results" in results:
                for task, metrics in results["results"].items():
                    # Prefer acc_norm, fall back to acc
                    score = metrics.get("acc_norm,none",
                            metrics.get("acc,none",
                            metrics.get("acc_norm",
                            metrics.get("acc"))))
                    if score is not None:
                        task_scores[task] = round(float(score), 4)

            eval_record: Dict[str, Any] = {
                "ts": int(time.time()),
                "model_path": resolved_path,
                "tasks": task_scores,
            }

            # Persist to KB
            if self.knowledge_db is not None:
                try:
                    self.knowledge_db.add_fact(
                        f"ale_lm_eval:{eval_record['ts']}",
                        eval_record,
                        tags=["eval", "lm_eval", "llm_architect"],
                    )
                except Exception:
                    pass

            self._stats["lm_eval_passes"] = self._stats.get("lm_eval_passes", 0) + 1

            score_str = "  ".join(
                f"{t}={v:.3f}" for t, v in task_scores.items()
            ) or "no scores extracted"
            result_msg = f"lm-eval: {score_str}"
            log.info("[LLMArchitect] %s", result_msg)
            return result_msg

        except Exception as exc:
            log.warning("[LLMArchitect] lm-eval-harness failed: %s", exc)
            return f"[lm-eval] Failed: {exc}"

    # ─────────────────────────────────────────────────────────────────────────
    # Full pipeline
    # ─────────────────────────────────────────────────────────────────────────

    def run_full_pipeline(self) -> str:
        """Run all pipeline stages in sequence: Curate → SFT → DPO → Eval → lm-eval."""
        self._stats["last_run_ts"] = int(time.time())
        parts = []

        try:
            parts.append(self.run_curation())
        except Exception as exc:
            parts.append(f"Curation error: {exc}")

        try:
            parts.append(self.run_sft())
        except Exception as exc:
            parts.append(f"SFT error: {exc}")

        try:
            parts.append(self.run_dpo())
        except Exception as exc:
            parts.append(f"DPO error: {exc}")

        try:
            parts.append(self.run_eval())
        except Exception as exc:
            parts.append(f"Eval error: {exc}")

        # Run lm-eval-harness after SFT when a local model is available
        local_model = os.environ.get("LOCAL_MODEL_PATH", "")
        if local_model and _LM_EVAL_AVAILABLE:
            try:
                parts.append(self.run_lm_eval_harness(local_model))
            except Exception as exc:
                parts.append(f"lm-eval error: {exc}")

        return " | ".join(parts)

    def status(self) -> Dict[str, Any]:
        """Return current engine statistics."""
        return {
            **self._stats,
            "torch_available": _TORCH_AVAILABLE,
            "trl_available": _TRL_AVAILABLE,
            "peft_available": _PEFT_AVAILABLE,
            "datasets_available": _DATASETS_AVAILABLE,
            "evaluate_available": _EVALUATE_AVAILABLE,
            "lm_eval_available": _LM_EVAL_AVAILABLE,
            "sft_dataset_path": str(_DATASET_PATH),
            "dpo_dataset_path": str(_PREF_DATASET_PATH),
            "finetune_output_dir": str(_FINETUNE_OUTPUT_DIR),
            "local_model_path": os.environ.get("LOCAL_MODEL_PATH", ""),
            "lm_eval_tasks": self._LM_EVAL_TASKS,
        }


# ── Singleton ─────────────────────────────────────────────────────────────────
_engine: Optional[LLMArchitectEngine] = None
_engine_lock = threading.Lock()


def get_llm_architect_engine(
    knowledge_db=None,
    brain_trainer=None,
    hf_brain=None,
    reward_model=None,
    llm_training_agent=None,
) -> LLMArchitectEngine:
    """Return the process-level LLMArchitectEngine singleton."""
    global _engine  # pylint: disable=global-statement
    with _engine_lock:
        if _engine is None:
            _engine = LLMArchitectEngine(
                knowledge_db=knowledge_db,
                brain_trainer=brain_trainer,
                hf_brain=hf_brain,
                reward_model=reward_model,
                llm_training_agent=llm_training_agent,
            )
        else:
            # Wire in any newly-available dependencies
            if knowledge_db is not None and _engine.knowledge_db is None:
                _engine.knowledge_db = knowledge_db
            if brain_trainer is not None and _engine.brain_trainer is None:
                _engine.brain_trainer = brain_trainer
            if hf_brain is not None and _engine.hf_brain is None:
                _engine.hf_brain = hf_brain
            if reward_model is not None and _engine.reward_model is None:
                _engine.reward_model = reward_model
            if llm_training_agent is not None and _engine.llm_training_agent is None:
                _engine.llm_training_agent = llm_training_agent
    return _engine
