#!/usr/bin/env python3
"""ale_python_natural_language_processing_with_nltk_an — natural language processing with NLTK and spaCy 1774034774

Auto-generated by Niblit ALE from autonomous research.
Research summary:
  Python is a high-level, general-purpose programming language. Its design
  philosophy emphasizes code readability with the use of significant
  indentation. Python is dynamically type-checked and garbage-collected.
"""

import re
import string
from collections import Counter
import logging
from typing import Any, Dict, List, Optional

log = logging.getLogger("ale_python_natural_language_processing_with_nltk_an")

# ── constants ────────────────────────────────────────────────────────
STOPWORDS = {
    'the', 'a', 'an', 'is', 'it', 'in', 'of', 'to', 'and', 'or',
    'for', 'on', 'at', 'by', 'with', 'that', 'this', 'was', 'are',
}
MAX_TOKENS = 512


# ── utility functions ────────────────────────────────────────────────
def tokenize(text: str) -> List[str]:
    """Split text into tokens, removing punctuation and stopwords."""
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    return [w for w in text.split() if w and w not in STOPWORDS]

def clean_text(text: str) -> str:
    """Normalise whitespace and lowercase text."""
    return re.sub(r'\s+', ' ', text).strip().lower()

def extract_keywords(text: str, top_n: int = 10) -> List[str]:
    """Return the top-N most frequent tokens."""
    tokens = tokenize(clean_text(text))
    freq = Counter(tokens)
    return [w for w, _ in freq.most_common(top_n)]

def ngrams(tokens: List[str], n: int = 2) -> List[tuple]:
    """Yield consecutive n-grams from a token list."""
    return [tuple(tokens[i:i + n]) for i in range(len(tokens) - n + 1)]


class AlePythonNaturalLanguageProcessingWithNltkAn:
    """AlePythonNaturalLanguageProcessingWithNltkAn — natural language processing with NLTK and spaCy 1774034774"""

    def __init__(self, language: str = 'en') -> None:
        self.language = language
        self._docs: List[str] = []
        log.debug('[%s] Initialized (lang=%s)', __name__, language)

    def process(self, text: str) -> Dict[str, Any]:
        """Tokenise, clean, and extract features from *text*."""
        cleaned = clean_text(text)
        tokens = tokenize(cleaned)
        keywords = extract_keywords(cleaned)
        bigrams = ngrams(tokens, 2)
        self._docs.append(cleaned)
        return {
            'original_length': len(text),
            'cleaned': cleaned,
            'tokens': tokens[:20],
            'keywords': keywords,
            'bigrams': [' '.join(b) for b in bigrams[:10]],
            'token_count': len(tokens),
        }

    def batch_process(self, texts: List[str]) -> List[Dict[str, Any]]:
        """Process a list of texts and return per-document results."""
        return [self.process(t) for t in texts]

    def run(self) -> Dict[str, Any]:
        """Return current statistics."""
        return {'documents_processed': len(self._docs), 'language': self.language}


if __name__ == "__main__":
    import logging as _logging
    _logging.basicConfig(level=_logging.INFO)
    obj = AlePythonNaturalLanguageProcessingWithNltkAn()
    print(obj.run())