#!/usr/bin/env python3
"""ale_python_reasoning_chains_and_multi_step_problem — reasoning chains and multi-step problem solving

Auto-generated by Niblit ALE from autonomous research.
Research summary:
  ✅ Researched python reasoning chains and multi-step problem solving: 2
  result(s) fetched. First result: No data found for 'python reasoning chains
  and multi-step problem solving code examples'...
"""

import re
import math
from collections import defaultdict
import logging
from typing import Any, Dict, List, Optional

log = logging.getLogger("ale_python_reasoning_chains_and_multi_step_problem")

# ── constants ────────────────────────────────────────────────────────
LOGIC_OPS = {
    'and': lambda a, b: a and b,
    'or':  lambda a, b: a or b,
    'not': lambda a, _: not a,
    'xor': lambda a, b: bool(a) != bool(b),
}
CONFIDENCE_THRESHOLD = 0.6


# ── utility functions ────────────────────────────────────────────────
def chain_of_thought(premises: List[str]) -> List[str]:
    """Apply simple forward chaining over a list of premise strings."""
    derived: List[str] = list(premises)
    for i, p in enumerate(premises):
        for j, q in enumerate(premises):
            if i != j and q.startswith(p.split()[-1]):
                conclusion = f'{p.split()[0]} → {q.split()[-1]}'
                if conclusion not in derived:
                    derived.append(conclusion)
    return derived

def score_confidence(evidence: List[float]) -> float:
    """Aggregate evidence weights into a single confidence score 0–1."""
    if not evidence:
        return 0.0
    return min(1.0, sum(evidence) / (len(evidence) * 1.0))

def extract_facts(text: str) -> List[str]:
    """Extract simple subject-verb-object facts from plain text."""
    sentences = re.split(r'[.!?]', text)
    return [s.strip() for s in sentences if len(s.strip().split()) >= 3]


class AlePythonReasoningChainsAndMultiStepProblem:
    """AlePythonReasoningChainsAndMultiStepProblem — reasoning chains and multi-step problem solving"""

    def __init__(self) -> None:
        self._knowledge: Dict[str, List[str]] = defaultdict(list)
        self._inferences: List[str] = []
        log.debug('[%s] Initialized', __name__)

    def add_fact(self, subject: str, predicate: str, obj: str) -> None:
        """Store a (subject, predicate, object) triple."""
        triple = f'{subject} {predicate} {obj}'
        self._knowledge[subject].append(triple)

    def infer(self, query: str) -> List[str]:
        """Return known facts whose subject matches *query*."""
        results = self._knowledge.get(query, [])
        chains = chain_of_thought(results)
        self._inferences.extend(chains)
        return chains

    def learn_from_text(self, text: str) -> int:
        """Extract and store facts from free text; return count added."""
        facts = extract_facts(text)
        for fact in facts:
            parts = fact.split(maxsplit=2)
            if len(parts) == 3:
                self.add_fact(*parts)
        return len(facts)

    def run(self) -> Dict[str, Any]:
        """Return knowledge-base statistics."""
        return {
            'subjects': len(self._knowledge),
            'total_facts': sum(len(v) for v in self._knowledge.values()),
            'inferences': len(self._inferences),
            'confidence_threshold': CONFIDENCE_THRESHOLD,
        }


if __name__ == "__main__":
    import logging as _logging
    _logging.basicConfig(level=_logging.INFO)
    obj = AlePythonReasoningChainsAndMultiStepProblem()
    print(obj.run())