#!/usr/bin/env python3
"""EventBus subscriber for NiblitDevAgent runtime awareness (Phase 2)."""

from __future__ import annotations

import logging
from collections import defaultdict, deque
from typing import Any

from agents.niblit_dev_agent.telemetry_hooks import DevAgentTelemetryHooks
from core.event_bus import Event, EventBus

log = logging.getLogger("NiblitDevAgent.EventSubscriber")

_MAX_RECENT = 50  # keep the last N events for reactive analysis


class EventSubscriber:
    """Observes EventBus traffic and suggests governed remediation workflows."""

    def __init__(self, event_bus: EventBus | None, telemetry: DevAgentTelemetryHooks) -> None:
        self._event_bus = event_bus
        self._telemetry = telemetry
        self._subscribed = False
        self._event_counts: dict[str, int] = defaultdict(int)
        self._category_counts: dict[str, int] = defaultdict(int)
        # Recent events for reactive analysis (bounded ring buffer)
        self._recent_events: deque[dict[str, Any]] = deque(maxlen=_MAX_RECENT)
        # Workflow suggestions generated by reactive handlers
        self._workflow_suggestions: list[dict[str, Any]] = []

    def subscribe(self) -> bool:
        if self._event_bus is None or self._subscribed:
            return False
        self._event_bus.subscribe_all(self._handle_event)
        self._subscribed = True
        return True

    def _handle_event(self, event: Event) -> None:
        etype = event.type.value
        self._event_counts[etype] += 1
        category = self._categorize_event(etype)
        self._category_counts[category] += 1

        self._telemetry.increment("dev_agent_events_total", 1)
        self._telemetry.increment(f"dev_agent_events_{category}_total", 1)
        self._telemetry.gauge("dev_agent_event_types_seen", float(len(self._event_counts)))

        entry: dict[str, Any] = {
            "type": etype,
            "category": category,
            "source": getattr(event, "source", "unknown"),
            "payload": dict(event.payload) if event.payload else {},
        }
        self._recent_events.append(entry)
        self._react(entry)

    def _react(self, entry: dict[str, Any]) -> None:
        """Generate governed workflow suggestions in response to notable events."""
        etype = entry["type"]
        et = etype.lower()

        suggestion: dict[str, Any] | None = None

        if "provider" in et and ("fail" in et or "error" in et or "unavailable" in et):
            suggestion = {
                "trigger": etype,
                "workflow": "provider_fallback_check",
                "description": (
                    "Provider failure detected. Suggested workflow: inspect provider "
                    "health via `dev-agent providers`, consider `llm-provider` switch."
                ),
                "governed_task_type": "provider_health_remediation",
                "severity": "high",
            }
        elif "test" in et and "fail" in et:
            suggestion = {
                "trigger": etype,
                "workflow": "test_failure_triage",
                "description": (
                    "Test failure event received. Suggested workflow: run architecture "
                    "analysis via `dev-agent analyze` to identify affected modules."
                ),
                "governed_task_type": "test_failure_analysis",
                "severity": "medium",
            }
        elif "runtime" in et and ("degrad" in et or "warn" in et or "error" in et):
            suggestion = {
                "trigger": etype,
                "workflow": "runtime_health_check",
                "description": (
                    "Runtime degradation event. Suggested workflow: inspect `dev-agent "
                    "runtime` topology, check event bus and thread counts."
                ),
                "governed_task_type": "runtime_degradation_analysis",
                "severity": "high",
            }
        elif "deploy" in et and ("mismatch" in et or "fail" in et or "conflict" in et):
            suggestion = {
                "trigger": etype,
                "workflow": "deployment_audit",
                "description": (
                    "Deployment mismatch event. Suggested workflow: compare "
                    "deployment boundaries via `dev-agent architecture`."
                ),
                "governed_task_type": "deployment_mismatch_remediation",
                "severity": "medium",
            }
        elif "route" in et and ("inconsist" in et or "fail" in et):
            suggestion = {
                "trigger": etype,
                "workflow": "router_inspection",
                "description": (
                    "Router inconsistency event. Suggested workflow: inspect "
                    "RouterV2 state via `dev-agent providers`."
                ),
                "governed_task_type": "router_inconsistency_analysis",
                "severity": "medium",
            }
        elif "architect" in et and "conflict" in et:
            suggestion = {
                "trigger": etype,
                "workflow": "architecture_conflict_resolution",
                "description": (
                    "Architecture conflict detected. Suggested workflow: full "
                    "architecture scan via `dev-agent analyze`."
                ),
                "governed_task_type": "architecture_conflict_resolution",
                "severity": "high",
            }

        if suggestion is not None:
            self._workflow_suggestions.append(suggestion)
            self._telemetry.increment("dev_agent_workflow_suggestions_total", 1)
            log.info(
                "[EventSubscriber] workflow suggestion emitted for event=%s workflow=%s",
                etype,
                suggestion["workflow"],
            )

    @staticmethod
    def _categorize_event(event_type: str) -> str:
        et = event_type.lower()
        if "provider" in et or "llm" in et:
            return "provider"
        if et.startswith("system_") or "boot" in et or "runtime" in et:
            return "runtime"
        if "deploy" in et or "environment" in et or "profile" in et:
            return "deployment"
        if "metric" in et or "telemetry" in et:
            return "telemetry"
        if "task" in et or "plan" in et or "orchestr" in et:
            return "orchestration"
        if "error" in et or "warn" in et:
            return "warning"
        return "other"

    def metrics(self) -> dict[str, Any]:
        return {
            "subscribed": self._subscribed,
            "events_total": int(sum(self._event_counts.values())),
            "event_types": dict(self._event_counts),
            "categories": dict(self._category_counts),
            "workflow_suggestions_total": len(self._workflow_suggestions),
        }

    def recent_events(self, n: int = 10) -> list[dict[str, Any]]:
        """Return the *n* most recently seen events (newest last)."""
        items = list(self._recent_events)
        return items[-n:]

    def workflow_suggestions(self) -> list[dict[str, Any]]:
        """Return all generated workflow suggestions (copy)."""
        return list(self._workflow_suggestions)

    def flush_suggestions(self) -> list[dict[str, Any]]:
        """Drain and return all pending workflow suggestions."""
        out = list(self._workflow_suggestions)
        self._workflow_suggestions.clear()
        return out

