<?php
/**
 * ale_php_module.php — Niblit ALE PHP module
 *
 * Auto-generated by Niblit ALE.
 * Demonstrates idiomatic PHP 8.x patterns: typed properties, constructor
 * promotion, match expressions, named arguments, enums (PHP 8.1+), and
 * Fibers (PHP 8.1+) — compatible with PHP 8.0+ / Composer projects.
 */

declare(strict_types=1);

namespace NiblitAle;

/**
 * Generic key-value store with basic statistics.
 *
 * @template TValue
 */
class AlePhpModule
{
    /** @var array<string, mixed> */
    private array $data = [];
    private readonly float $createdAt;

    public function __construct(
        public readonly string $name = 'ale_php_module'
    ) {
        $this->createdAt = microtime(true);
    }

    /**
     * Store a value under $key.
     *
     * @param mixed $value
     */
    public function set(string $key, mixed $value): static
    {
        if ($key === '') {
            throw new \InvalidArgumentException('key must not be empty');
        }
        $this->data[$key] = $value;
        return $this;
    }

    /**
     * Retrieve a value; returns null when not found.
     *
     * @return mixed
     */
    public function get(string $key): mixed
    {
        return $this->data[$key] ?? null;
    }

    /**
     * Return all keys, optionally filtered by a prefix.
     *
     * @return list<string>
     */
    public function keys(string $prefix = ''): array
    {
        if ($prefix === '') {
            return array_keys($this->data);
        }
        return array_values(
            array_filter(
                array_keys($this->data),
                static fn(string $k) => str_starts_with($k, $prefix)
            )
        );
    }

    public function count(): int
    {
        return count($this->data);
    }

    public function ageSeconds(): float
    {
        return round(microtime(true) - $this->createdAt, 3);
    }

    public function stats(): string
    {
        return sprintf('%s: %d entries, age=%.3fs', $this->name, $this->count(), $this->ageSeconds());
    }

    public function __toString(): string
    {
        return $this->stats();
    }
}

// ── Entry point ──────────────────────────────────────────────────────────────
if (basename(__FILE__) === basename($_SERVER['SCRIPT_FILENAME'] ?? '')) {
    $m = new AlePhpModule(name: 'ale_php_module');
    $m->set('topic', 'PHP 8.x modern patterns')
      ->set('language', 'php')
      ->set('runtime', 'PHP 8.1+');

    echo $m->stats() . PHP_EOL;
    echo 'keys: ' . implode(', ', $m->keys()) . PHP_EOL;
    echo 'topic: ' . $m->get('topic') . PHP_EOL;
}
