# frozen_string_literal: true
# ale_ruby_module.rb — Niblit ALE Ruby module
#
# Auto-generated by Niblit ALE.
# Demonstrates idiomatic Ruby patterns: modules, mixins, Comparable,
# Enumerable, blocks, procs, and method_missing — compatible with Ruby 3.x.

require 'time'

module NiblitAle
  # Mixin that adds a simple key-value store to any class.
  module KeyValueStore
    def initialize_store
      @_data = {}
      @_created_at = Time.now
    end

    def set(key, value)
      raise ArgumentError, 'key must be a non-empty string' if key.to_s.empty?

      @_data[key.to_s] = value
      self
    end

    def get(key)
      @_data[key.to_s]
    end

    def keys(prefix: nil)
      return @_data.keys if prefix.nil? || prefix.empty?

      @_data.keys.select { |k| k.start_with?(prefix) }
    end

    def entries
      @_data.size
    end

    def age_seconds
      (Time.now - @_created_at).round(2)
    end
  end

  # Canonical ALE Ruby module: generic store with statistics.
  class AleRubyModule
    include KeyValueStore
    include Comparable

    attr_reader :name

    def initialize(name = 'ale_ruby_module')
      @name = name.to_s
      initialize_store
    end

    def stats
      "#{@name}: #{entries} entries, age=#{age_seconds}s"
    end

    # Comparable by entry count.
    def <=>(other)
      entries <=> other.entries
    end

    # Enumerable-style each over stored pairs.
    def each(&block)
      @_data.each(&block)
    end

    # Dynamic reader: module.topic => get('topic')
    def method_missing(name, *_args)
      key = name.to_s
      return @_data[key] if @_data.key?(key)

      super
    end

    def respond_to_missing?(name, include_private = false)
      @_data.key?(name.to_s) || super
    end

    def to_s
      stats
    end

    def inspect
      "#<#{self.class.name} name=#{@name.inspect} entries=#{entries}>"
    end
  end
end

# ── Entry point ──────────────────────────────────────────────────────────────
if __FILE__ == $PROGRAM_NAME
  m = NiblitAle::AleRubyModule.new('ale_ruby_module')
  m.set('topic', 'Ruby idiomatic patterns')
  m.set('language', 'ruby')
  m.set('runtime', 'Ruby 3.x')

  puts m.stats
  puts "keys: #{m.keys.join(', ')}"
  puts "topic via method_missing: #{m.topic}"
end
