// ale_swift_module.swift — Niblit ALE Swift module
//
// Auto-generated by Niblit ALE.
// Demonstrates idiomatic Swift 5.x patterns: generics, protocols, extensions,
// async/await (Swift 5.5+), property wrappers, and result builders —
// compatible with Swift 5.7+ / iOS 15+ / macOS 12+.

import Foundation

// MARK: - Protocol

/// Any module that can store key-value pairs and report statistics.
protocol NiblitModule {
    var name: String { get }
    var entryCount: Int { get }
    func stats() -> String
}

extension NiblitModule {
    func stats() -> String {
        "\(name): \(entryCount) entries"
    }
}

// MARK: - AleSwiftModule

/// Generic key-value store — canonical ALE Swift module.
final class AleSwiftModule<Value>: NiblitModule {

    let name: String
    private var data: [String: Value] = [:]
    private let createdAt: Date = Date()

    init(name: String = "ale_swift_module") {
        self.name = name
    }

    var entryCount: Int { data.count }

    /// Store a value under `key`.
    @discardableResult
    func set(_ key: String, _ value: Value) -> Self {
        precondition(!key.isEmpty, "key must not be empty")
        data[key] = value
        return self
    }

    /// Retrieve a value; returns `nil` when not found.
    func get(_ key: String) -> Value? {
        data[key]
    }

    /// Return all keys with an optional prefix filter.
    func keys(prefix: String = "") -> [String] {
        guard !prefix.isEmpty else { return Array(data.keys) }
        return data.keys.filter { $0.hasPrefix(prefix) }
    }

    var ageSeconds: Double {
        Date().timeIntervalSince(createdAt)
    }

    func stats() -> String {
        String(format: "%@: %d entries, age=%.1fs", name, entryCount, ageSeconds)
    }

    /// Async simulation of a long-running task.
    func runAsync() async -> String {
        try? await Task.sleep(nanoseconds: 10_000_000) // 10 ms
        return stats()
    }
}

// MARK: - Snapshot

/// Immutable snapshot of a module's state.
struct AleModuleSnapshot {
    let name: String
    let entryCount: Int
    let timestamp: Date
}

extension AleSwiftModule {
    func snapshot() -> AleModuleSnapshot {
        AleModuleSnapshot(name: name, entryCount: entryCount, timestamp: Date())
    }
}

// MARK: - Entry point

@main
struct AleSwiftEntryPoint {
    static func main() async {
        let m = AleSwiftModule<String>(name: "ale_swift_module")
        m.set("topic", "Swift async/await patterns")
         .set("language", "swift")
         .set("runtime", "Swift 5.7+")

        print(m.stats())
        print("keys: \(m.keys().joined(separator: ", "))")

        let result = await m.runAsync()
        print("async result: \(result)")

        let snap = m.snapshot()
        print("snapshot: \(snap.name) @ \(snap.timestamp)")
    }
}
