#!/usr/bin/env python3
"""Real module generated by LLM."""

import logging
log = logging.getLogger(__name__)

class DataProcessor:
    """Processes data with best practices."""
    
    def __init__(self):
        self.results = []
    
    def process(self, data):
        """Apply processing pipeline."""
        result = [x for x in data if x is not None]
        self.results.extend(result)
        log.info("Processed %d items", len(result))
        return result

if __name__ == "__main__":
    proc = DataProcessor()
    print(proc.process([1, 2, None, 3]))
