#!/usr/bin/env python3
"""ale_python_chat_completion_api_client_implementatio — chat completion API client implementations 1773950585

Auto-generated by Niblit ALE from autonomous research.
Research summary:
  PostgreSQL, also known as Postgres, is a free and open-source relational
  database management system (RDBMS) emphasizing extensibility and SQL
  compliance. PostgreSQL features transactions with atomicity, consistency,
  isolation, durability (ACID) properties, automatically updatable views,
  materialized
"""

import json
import time
import logging
from typing import Any, Dict, List, Optional

log = logging.getLogger("ale_python_chat_completion_api_client_implementatio")

# ── constants ────────────────────────────────────────────────────────
VALID_ROLES = ('system', 'user', 'assistant')
DEFAULT_MAX_TOKENS = 2048
DEFAULT_TEMPERATURE = 0.7


# ── utility functions ────────────────────────────────────────────────
def build_message(role: str, content: str) -> Dict[str, str]:
    """Validate and build a chat message dict."""
    if role not in VALID_ROLES:
        raise ValueError(f'role must be one of {VALID_ROLES}')
    return {'role': role, 'content': content.strip()}

def truncate_history(
    history: List[Dict[str, str]],
    max_messages: int = 20,
) -> List[Dict[str, str]]:
    """Keep the system message plus the most-recent *max_messages* turns."""
    system = [m for m in history if m.get('role') == 'system']
    turns = [m for m in history if m.get('role') != 'system']
    return system + turns[-max_messages:]


class AlePythonChatCompletionApiClientImplementatio:
    """AlePythonChatCompletionApiClientImplementatio — chat completion API client implementations 1773950585"""

    def __init__(self, system_prompt: str = 'You are a helpful assistant.') -> None:
        self.history: List[Dict[str, str]] = [
            build_message('system', system_prompt)
        ]
        self._created_at: float = time.time()
        log.debug('[%s] Initialized', __name__)

    def send(self, user_input: str) -> Dict[str, Any]:
        """Append a user turn and return the payload for an LLM API call."""
        self.history.append(build_message('user', user_input))
        payload = {
            'messages': self.history,
            'max_tokens': DEFAULT_MAX_TOKENS,
            'temperature': DEFAULT_TEMPERATURE,
        }
        return payload

    def receive(self, assistant_reply: str) -> None:
        """Record an assistant reply in the conversation history."""
        self.history.append(build_message('assistant', assistant_reply))
        self.history = truncate_history(self.history)

    def clear(self) -> None:
        """Reset conversation history (keeps the system prompt)."""
        self.history = [m for m in self.history if m.get('role') == 'system']

    def run(self) -> Dict[str, Any]:
        """Return conversation statistics."""
        turns = [m for m in self.history if m.get('role') != 'system']
        return {
            'turns': len(turns),
            'history_bytes': len(json.dumps(self.history)),
            'uptime_s': round(time.time() - self._created_at, 1),
        }


if __name__ == "__main__":
    import logging as _logging
    _logging.basicConfig(level=_logging.INFO)
    obj = AlePythonChatCompletionApiClientImplementatio()
    print(obj.run())