#!/usr/bin/env python3
"""ale_python_code_structure_and_indentation_177389191 — code structure and indentation 1773891918

Auto-generated by Niblit ALE from autonomous research.
Research summary:
  Python is a high-level, general-purpose programming language. Its design
  philosophy emphasizes code readability with the use of significant
  indentation. Python is dynamically type-checked and garbage-collected.
"""

import csv
import json
import os
from pathlib import Path
import logging
from typing import Any, Dict, List, Optional

log = logging.getLogger("ale_python_code_structure_and_indentation_177389191")

# ── constants ────────────────────────────────────────────────────────
DEFAULT_ENCODING = 'utf-8'
MAX_ROWS = 10_000


# ── utility functions ────────────────────────────────────────────────
def read_jsonl(path: str) -> List[Dict[str, Any]]:
    """Read a newline-delimited JSON file and return a list of records."""
    records: List[Dict[str, Any]] = []
    with open(path, encoding=DEFAULT_ENCODING) as fh:
        for line in fh:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records[:MAX_ROWS]

def write_jsonl(records: List[Dict[str, Any]], path: str) -> int:
    """Write *records* to a JSONL file; returns number of records written."""
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w', encoding=DEFAULT_ENCODING) as fh:
        for rec in records:
            fh.write(json.dumps(rec, ensure_ascii=False) + '\n')
    return len(records)

def flatten(d: Dict[str, Any], prefix: str = '') -> Dict[str, Any]:
    """Recursively flatten a nested dict with dot-separated keys."""
    items: Dict[str, Any] = {}
    for k, v in d.items():
        key = f'{prefix}.{k}' if prefix else k
        if isinstance(v, dict):
            items.update(flatten(v, key))
        else:
            items[key] = v
    return items


class AlePythonCodeStructureAndIndentation177389191:
    """AlePythonCodeStructureAndIndentation177389191 — code structure and indentation 1773891918"""

    def __init__(self, data_dir: str = '.') -> None:
        self.data_dir = Path(data_dir)
        self._records: List[Dict[str, Any]] = []
        log.debug('[%s] Initialized (dir=%s)', __name__, data_dir)

    def load(self, filename: str) -> int:
        """Load records from a JSONL file under *data_dir*."""
        path = str(self.data_dir / filename)
        self._records = read_jsonl(path)
        log.info('[%s] Loaded %d records from %s',
                 __name__, len(self._records), filename)
        return len(self._records)

    def save(self, filename: str) -> int:
        """Persist current records to *filename* under *data_dir*."""
        path = str(self.data_dir / filename)
        n = write_jsonl(self._records, path)
        log.info('[%s] Saved %d records to %s', __name__, n, filename)
        return n

    def filter(self, **kwargs: Any) -> List[Dict[str, Any]]:
        """Return records where every key=value pair matches."""
        result = self._records
        for key, val in kwargs.items():
            result = [r for r in result if r.get(key) == val]
        return result

    def run(self) -> Dict[str, Any]:
        """Return dataset statistics."""
        keys: set = set()
        for r in self._records:
            keys.update(r.keys())
        return {
            'records': len(self._records),
            'fields': sorted(keys),
            'data_dir': str(self.data_dir),
        }


if __name__ == "__main__":
    import logging as _logging
    _logging.basicConfig(level=_logging.INFO)
    obj = AlePythonCodeStructureAndIndentation177389191()
    print(obj.run())