#!/usr/bin/env python3
"""ale_python_socket_programming_and_networking_177489 — socket programming and networking 1774894711

Auto-generated by Niblit ALE from autonomous research.
Research summary:
  JavaScript (JS) is a programming language and core technology of the Web,
  alongside HTML and CSS. It was created by Brendan Eich in 1995. As of 2025,
  the overwhelming majority of websites (98.9%) uses JavaScript for client
  side webpage behavior.
"""

import urllib.request
import urllib.error
import json
import time
import logging
from typing import Any, Dict, List, Optional

log = logging.getLogger("ale_python_socket_programming_and_networking_177489")

# ── constants ────────────────────────────────────────────────────────
DEFAULT_TIMEOUT = 30
MAX_RETRIES = 3
RETRY_DELAY = 2.0


# ── utility functions ────────────────────────────────────────────────
def http_get(url: str, headers: Optional[Dict[str, str]] = None,
             timeout: int = DEFAULT_TIMEOUT) -> Dict[str, Any]:
    """Simple HTTP GET with retry logic; returns parsed JSON or raw text."""
    req = urllib.request.Request(url, headers=headers or {})
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                raw = resp.read().decode('utf-8', errors='replace')
                try:
                    return {'ok': True, 'data': json.loads(raw), 'status': resp.status}
                except json.JSONDecodeError:
                    return {'ok': True, 'data': raw, 'status': resp.status}
        except urllib.error.URLError as exc:
            if attempt == MAX_RETRIES:
                return {'ok': False, 'error': str(exc), 'status': None}
            time.sleep(RETRY_DELAY * attempt)
    return {'ok': False, 'error': 'max retries exceeded', 'status': None}


class AlePythonSocketProgrammingAndNetworking177489:
    """AlePythonSocketProgrammingAndNetworking177489 — socket programming and networking 1774894711"""

    def __init__(self, base_url: str = '', api_key: str = '') -> None:
        self.base_url = base_url.rstrip('/')
        self._headers: Dict[str, str] = {}
        if api_key:
            self._headers['Authorization'] = f'Bearer {api_key}'
        log.debug('[%s] Initialized (base=%s)', __name__, self.base_url)

    def get(self, path: str, extra_headers: Optional[Dict[str, str]] = None
            ) -> Dict[str, Any]:
        """Perform GET *base_url/path* and return parsed response."""
        url = f'{self.base_url}/{path.lstrip("/")}'
        headers = {**self._headers, **(extra_headers or {})}
        return http_get(url, headers=headers)

    def health_check(self) -> bool:
        """Return True if the API base URL is reachable."""
        if not self.base_url:
            return False
        result = http_get(self.base_url, headers=self._headers, timeout=5)
        return result.get('ok', False)

    def run(self) -> Dict[str, Any]:
        """Return client configuration summary."""
        return {
            'base_url': self.base_url,
            'has_auth': bool(self._headers.get('Authorization')),
            'timeout': DEFAULT_TIMEOUT,
        }


if __name__ == "__main__":
    import logging as _logging
    _logging.basicConfig(level=_logging.INFO)
    obj = AlePythonSocketProgrammingAndNetworking177489()
    print(obj.run())