// ale_csharp_module.cs — Niblit ALE C# module
//
// Auto-generated by Niblit ALE.
// Demonstrates idiomatic C# patterns: properties, generics, LINQ, async/await,
// and record types — ready to compile with .NET 6+ or Unity.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NiblitAle
{
    /// <summary>
    /// Generic key-value store with basic statistics — canonical ALE C# module.
    /// </summary>
    /// <typeparam name="TValue">The value type stored in the module.</typeparam>
    public class AleCsharpModule<TValue>
    {
        private readonly Dictionary<string, TValue> _data = new();
        private readonly DateTime _createdAt = DateTime.UtcNow;

        public string Name { get; }

        public AleCsharpModule(string name = "ale_csharp_module")
        {
            Name = name ?? throw new ArgumentNullException(nameof(name));
        }

        /// <summary>Store a value under <paramref name="key"/>.</summary>
        public void Set(string key, TValue value)
        {
            if (string.IsNullOrEmpty(key)) throw new ArgumentException("key must not be empty", nameof(key));
            _data[key] = value;
        }

        /// <summary>Retrieve a value; returns <c>default</c> when not found.</summary>
        public TValue? Get(string key) =>
            _data.TryGetValue(key, out var v) ? v : default;

        /// <summary>Return all keys matching an optional prefix filter.</summary>
        public IEnumerable<string> Keys(string prefix = "") =>
            string.IsNullOrEmpty(prefix)
                ? _data.Keys
                : _data.Keys.Where(k => k.StartsWith(prefix, StringComparison.Ordinal));

        /// <summary>Human-readable summary.</summary>
        public string Stats()
        {
            var age = DateTime.UtcNow - _createdAt;
            return $"{Name}: {_data.Count} entries, age={age.TotalSeconds:F1}s";
        }

        /// <summary>Async wrapper for long-running process simulation.</summary>
        public async Task<string> RunAsync(int delayMs = 10)
        {
            await Task.Delay(delayMs);
            return Stats();
        }
    }

    /// <summary>Immutable snapshot record (C# 9+ record type).</summary>
    public record AleModuleSnapshot(string Name, int EntryCount, DateTime CreatedAt);

    // ── Entry point ────────────────────────────────────────────────────────
    internal static class Program
    {
        static async Task Main(string[] _)
        {
            var m = new AleCsharpModule<string>("ale_csharp_module");
            m.Set("topic", "C# .NET patterns");
            m.Set("language", "csharp");
            m.Set("runtime", ".NET 6+");

            Console.WriteLine(m.Stats());
            Console.WriteLine(string.Join(", ", m.Keys()));

            var result = await m.RunAsync();
            Console.WriteLine($"async result: {result}");

            var snap = new AleModuleSnapshot(m.Name, m.Keys().Count(), DateTime.UtcNow);
            Console.WriteLine($"snapshot: {snap}");
        }
    }
}
